### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Grolar1337** [tari-project/wallet-ios#1015]
test

**Comment by TruszczynskiA** [comment]
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOTBoeXY0Znp4N3Z6aWY0M3V6eGdvajkycHdjbGl3aGY4cWNmanJvYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Nx0rz3jtxtEre/giphy.gif)
