### ISSUE TITLE
[Feature] New user - Introduction to wallet

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#103]
See [parent](https://github.com/tari-project/tari/issues/1219)

**Comment by Jasonvdb** [comment]
@karim-tari I tried to animate this wave myself and didn't come out right. Can you export the lottie file for this?
<img width="355" alt="Screenshot 2020-02-07 at 11 16 30" src="https://user-images.githubusercontent.com/5300488/74016898-e6d99880-499b-11ea-8ed0-fcb4a82b8bd1.png">

**Comment by Karim-tari** [comment]
@Jasonvdb will do. I'll try to get that in our Dropbox folder soon.
