### ISSUE TITLE
[Feature] Notify user when they are sent Tari

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#106]
See [parent](https://github.com/tari-project/tari/issues/1226)

**Comment by Anziskavds** [comment]
Tested unsuccessfully. I received a push notification that I've been sent some Tari but when I clicked on the notification the app stopped and didn't redirect me to my Tari wallet. I didn't have the app open while testing this.

![image](https://user-images.githubusercontent.com/50451670/80498651-47a9b900-896c-11ea-8fe5-a802f9a63ff6.png)
