### ISSUE TITLE
Refactor lib and all implementations to use `Tx` instead of `Transaction` everywhere

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#109]

**Comment by SerhiiShovkoplias** [comment]
it is only code base refactoring. It should not have influence to visual in app

**Comment by Anziskavds** [comment]
Closing off this card as per @SerhiiShovkoplias comment above. This is only code-based and no testing that can be done.

cc @Tas4tari @Jasonvdb
