### ISSUE TITLE
When clicking on Enable screenshot, it takes you to the wrong screen

### ISSUE THREAD

**Issue by stringhandler** [tari-project/wallet-ios#1108]
Version: v0.27.0 (b746)

Steps to reproduce:
1. On a screen press power + home button to take a screenshot
1. On the "no problems, mate" popup, click Enable screenshots

Expected:
Some screenshot settings

Actual:
Security screen is shown with no screenshot settings

**Comment by Anziskavds** [comment]
Failed QA. The issue still remains on Aurora Esmeralda v0.27.0(b748)
