### ISSUE TITLE
Error popup can only be dismissed by waiting

### ISSUE THREAD

**Issue by stringhandler** [tari-project/wallet-ios#1115]
You can't click on the error popups to dismiss them and you have to wait for them to disappear to use the app again

**Comment by TruszczynskiA** [comment]
You can also dismiss it interactively (by swiping it down).

**Comment by stringhandler** [comment]
I didn't realise this, but I think most users will also not realise this. In iOs, most of these toasts react to being tapped, so it felt really frustrating for me that I had to wait for it

**Comment by TruszczynskiA** [comment]
This is agains the App design guild.

**Comment by stringhandler** [comment]
I am not familiar with these. @TruszczynskiA do you have a link to these specifically so I can familiarise myself. I tried searching for Toast and Popover but this component doesn't seem to be either of them
