### ISSUE TITLE
Seed phrase wallet recovery doesn't work

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-ios#1122]
**Describe the bug**
Wallet recovery with seed phrase doesn't work on the new build on iOS. User receives an error saying that there was something wrong with the address. I couldn't take a screenshot because it's not enabled and I can't enable it before the wallet is setup.

**To Reproduce**
1. Install the new build 
2. Click on Restore wallet
3. Select the seed phrase option
4. Add wallet address and seed phrase
5. Click on Done
6. User receives an error saying that wallet couldn't be restore because there is something wrong with the address

**Expected behavior**
User should be able to successfully restore their wallet with their seed phrase

**Screenshots**
Screenshots are disabled and I am unable to enable screenshots before the wallet setup.

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 17.5.1
 - Browser & Version Safari browser on Esmeralda v0.27.0(b748)

**Additional context**
Recovery worked when I selected to restore the wallet from the icloud

**Comment by TruszczynskiA** [comment]
Unable to reproduce in FFI v1.4.0

**Comment by Anziskavds** [comment]
Tested successfully on Aurora ESMERALDA v0.27.0 (b750) on an iPhone 12 iOS 17.5.1.
