### ISSUE TITLE
Can't click on antenna icon

### ISSUE THREAD

**Issue by stringhandler** [tari-project/wallet-ios#1130]
v0.27.0 b753

Can't click on Wifi/Antenna icon on home screen.

**Comment by TruszczynskiA** [comment]
It's known issue related to SwiftEntryKit. Please kill your app and try again

**Comment by Anziskavds** [comment]
Tested successfully on iPhone 12 iOS 17.6.1 on ESMERALDA v0.27.0 (b756).
