### ISSUE TITLE
Custom animated values UILabel

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#123]
A reusable animated UILabel that animates every time the number value is changed.

The component will be used on the app's home screen and will animate every time the user receives or sends Tari as well as on the select amount screen when sending Tari.

Currently we only have the home screen but the label should be reusable in any part of the app.

Animation at `1:43` and `2:26`: 
https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0

**Comment by Jasonvdb** [comment]
Hey @karim-tari, Semih is working on this task now. Originally I assumed the 2 different instances of this animation were the same but it seems the home view balance and when you're entering an amount to send behave a little different. I've told him to go ahead and  standardize on the first animation, is that fine?

**Comment by Karim-tari** [comment]
@Jasonvdb Thanks, yeah that makes sense. I agree they should be consistent.
