### ISSUE TITLE
Correctly handle optional dates in sorted callback

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#129]
https://github.com/tari-project/wallet-ios/pull/126#discussion_r376875872

**Comment by kukabi** [comment]
@Jasonvdb Is this still an issue?

**Comment by Jasonvdb** [comment]
@kukabi it's still there but there's never been an actual issue caused by this code so can probably close

**Comment by TruszczynskiA** [comment]
This is no longer an issue.
