### ISSUE TITLE
QA: Animation when new user first opens app

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#159]
**Reference**

00:00 - 01:07 of Karim's QA video (turn on audio, he speaks through it all): https://www.dropbox.com/s/bu7ifjngymu2907/Feedback-Splash-Screen.mp4?dl=0

00:00 - 00:06 of reference design video for NEW users:
https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0

00:00- 00:06 of this video for EXISTING users (already created wallet): https://vimeo.com/369345180

**Fixes:**

- Timing and UI should be identical to reference video. (Suggestion: an easy way to test this during development is by hitting play on video at the same time as opening your build locally to make sure it's nearly identical
- Gem is too small, please refer to dimensions in https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5dbdf23a10500582e6799fe3
- Gem should appear for 2 seconds if new user, should start fading as soon as app is fully in foreground for existing users
- Gem should fade out over 1 second
- Screen should stay black for about 750 ms

**Comment by talmahaj** [comment]
@Jasonvdb have you been assigning to @lupugabriel just by tagging him here or DMing him on MM?

**Comment by Jasonvdb** [comment]
DMing and he's been following asana
