### ISSUE TITLE
QA: Splash screen and animations

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#160]
**Reference**

Watch 01:08 onwards of Karim's QA video (turn on audio, he speaks through it all): https://www.dropbox.com/s/bu7ifjngymu2907/Feedback-Splash-Screen.mp4?dl=0

QA screenshot of build vs. spec: 
![Screen Shot 2020-03-03 at 6.44.50 PM.png](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/b41dd6d7-43fa-487e-9b82-e9847188f9cd)

00:06-00:31 of reference design video:
https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0

Zeplin spec: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e25463cf04d2c2a8086b43c

**Fixes:**

- Spacing, gutters, sizes, and type line height & kerning should be identical to Zeplin file. Pls click each element  and each gutter/whitespace in zeplin to confirm everything is built to spec including asset size, border radius, etc. It's helpful to take screenshots and compare to design to ensure it's pixel perfect.
- Orb is too small
- Tari logo doesn't appear to be using correct asset and is wrong size
- Each line of heading should animate in on its own per Karim's QA video
- All elements other than heading should fade in at the same time
- Loading state of button is missing, should be spinning circle per 00:25-00:27 of reference video and should last about 2 seconds per the video
- After button loading state, everything should disappear except Tari logo per reference video
- The splash screen is not supposed to appear for users who already have wallets. Existing user loading animation is per 00:00-00:11 of this video: https://vimeo.com/369345180
- Timing and UI should be identical to reference video. (Suggestion: an easy way to test this during development is by hitting play on video at the same time as opening your build locally to make sure it's nearly identical

**Comment by talmahaj** [comment]
@karim-tari 

@karim-tari will supply a new video for the orb soon that will just fade in/out through the video so we can loop that automatically. (No need to stress the CPU by doing an in-code fade)

@karim-tari what should dimensions of orb be?

**Comment by Jasonvdb** [comment]
@lupugabriel can you have a look at these. I think maybe run through and do all the quick changes that are mostly sizing updates. But for the more involved one's let's discuss here.

**Comment by talmahaj** [comment]
@Jasonvdb can you send me a build for this one and the other QA ticket in UAT so Karim and I can take a look? Thanks!

**Comment by talmahaj** [comment]
Also @Jasonvdb does this already use the updated purple orb file at https://www.dropbox.com/sh/3mon1qlmuvmkjft/AADq58Ox0roNCTePD7bdJvtfa?dl=0 ?

**Comment by Jasonvdb** [comment]
@talmahaj there's a PR in for this right now that I'm busy reviewing, once it's merged I'll send out a testflight for you and Karim to review again. I believe it has the new orb video.

**Comment by lupugabriel** [comment]
Hi everybody @Jasonvdb @talmahaj @karim ( i can't tag Karim ).
I what i did for the current PR:
1. Added a black view when the app opens. Then the black view fade away in one second ( Karim request on video )
2. Animation of the second line of the title.  ( Karim request in video )
3. Spacing checked like in Zeplin ( The app was tested to be 100% like zeplin for iPhone X )
4. Replaced old video with current one: purple_orb i received from Android team
5. after create wallet is pressed everything else fade away and the Tari title goes in the middle of the screen and then animate it.
6. The Orb Video is bigger or smaller depending of the dimension of the phone.

**Comment by lupugabriel** [comment]
Iphone 11 pro max
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-09 at 12 09 40](https://user-images.githubusercontent.com/3657507/76217425-50063300-620a-11ea-8fe0-d64b1bd33ad4.png)
iPhone 11 Pro
![Simulator Screen Shot - iPhone 11 Pro - 2020-03-09 at 12 08 35](https://user-images.githubusercontent.com/3657507/76217439-54cae700-620a-11ea-8f82-aa4c438a7d8b.png)
iPhone X
![Simulator Screen Shot - iPhone X - 2020-03-09 at 12 04 58](https://user-images.githubusercontent.com/3657507/76217442-55637d80-620a-11ea-84a5-d04b9204aaaa.png)
iPhone 8
![Simulator Screen Shot - iPhone 8 - 2020-03-09 at 12 11 14](https://user-images.githubusercontent.com/3657507/76217447-55fc1400-620a-11ea-946c-085ce2a54a66.png)

**Comment by lupugabriel** [comment]
Let me know what you think about this version and ill fix any comments asap. thanks.
