### ISSUE TITLE
QA: Wallet Creation Flow

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#167]
**Reference**

Watch up to 4:20 of Karim's QA video (turn on audio, he speaks through it all) and obviously ignore the part about 12 emojis since that's outdated now: https://www.dropbox.com/s/x634sgaij2f3nvu/Feedback-Wallet-Creation.mp4?dl=0

00:31-1:39 of reference design video:
https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0

Zeplin screen specs: See relevant sections in Zeplin

Comparisons of key screens:
![Screen Shot 2020-03-03 at 8.47.57 PM.png](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/28f242e6-71b3-41c7-a4e9-f7d34bddc723)![Screen Shot 2020-03-03 at 8.47.37 PM.png](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/faa68f8e-fe1e-487f-9729-320d9ea89239)![Screen Shot 2020-03-03 at 8.47.17 PM.png](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/f0c2f9f6-0400-4a2f-afca-a6205fd612be)![Screen Shot 2020-03-03 at 8.47.06 PM.png](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/febe8368-77cf-48fd-a3e3-9de69b6e0ecd)

**Changes (not bugs):**

- Remove Tari logo from top and add ring loading indicator per video -- this was changed from when Zeplin screens were first exported so hope you don't mind making this change while you're working on the other stuff. @karim-tari please provide the ring loading indicator file, thanks.
- Make "Hello Friend" text bigger per the newer design Karim shows in the video -- @karim-tari how big is it in the video? We only have the smaller text version.

**Tal's Fixes:**

- Spacing, gutters, sizes, and type line height & kerning should be identical to Zeplin file. Pls click each element  and each gutter/whitespace in zeplin to confirm everything is built to spec including asset size, border radius, etc. It's helpful to take screenshots and compare to design to ensure it's pixel perfect.
- If it isn't already, timing and UI should be identical to reference video. (Suggestion: an easy way to test this during development is by hitting play on video at the same time as opening your build locally to make sure it's nearly identical
- General
    - Correct background colors; many screens are #F6F6F6 and not pure white
- Nerd emoji screen fixes:
    - Content in center of screen is too high up
    - Emoji too large
    - Gutters too big, text should not wrap to 3rd line
    - Corner radius on button
    - Gradient colors
- Emoji ID screen fixes:
    - Vertical whitespace between emoji ID and content
    - White background behind emoji ID missing shadow
    - Content in center of screen too high
    - Button corner radius and gradient colors
- Face ID screen fixes:
    - Shadow behind graphic is missing
    - Skip button missing
    - Content too high up
    - Button corner radius and gradient colors
- Hello Friend/checkmark
    - Content too high
    - Make checkmark bigger per Zeplin
- Animations
    - The black text on each step is not supposed to fade in, but each line is supposed to appear in/slide in from the bottom per Karim's QA video
    - Emoji wheel is a bit off and has a moment where it stops in the middle, see Karim's QA video
    - Face ID is missing the lottie animation
    - On the "Hello! This is your Tari Wallet" screen the waving animation is a bit off. (We have a lottie file for this).
    - Skip button is missing
- Other
    - Notifications authorization screen is missing
- Face ID behavior
    - Screen should not change to the wave hand emoji screen until AFTER user finishes local authentication. Currently it changes at the same time as the OS' local authentication face ID/touch ID modal appears
    - Screen background is supposed to go dark behind OS local authentication modal
- "Hello" screen with waving hand
    - Top part should be higher and sharper corners per designs
    - Background should be dimmed

**Comment by talmahaj** [comment]
@Jasonvdb FYI new QA ticket! You and/or Lupu did awesome work on these animations.

**Comment by lupugabriel** [comment]
Changes (not bugs):

- [ ] Remove Tari logo from top and add ring loading indicator per video -- this was changed from when Zeplin screens were first exported so hope you don't mind making this change while you're working on the other stuff. @Karim-tari please provide the ring loading indicator file, thanks.

- [ ] Make "Hello Friend" text bigger per the newer design Karim shows in the video -- @Karim-tari how big is it in the video? We only have the smaller text version.

Tal's Fixes:

- [ ] Spacing, gutters, sizes, and type line height & kerning should be identical to Zeplin file. Pls click each element and each gutter/whitespace in zeplin to confirm everything is built to spec including asset size, border radius, etc. It's helpful to take screenshots and compare to design to ensure it's pixel perfect.

- [ ] If it isn't already, timing and UI should be identical to reference video. (Suggestion: an easy way to test this during development is by hitting play on video at the same time as opening your build locally to make sure it's nearly identical

General

- [ ] Correct background colors; many screens are #F6F6F6 and not pure white

Nerd emoji screen fixes:

- [ ] Content in center of screen is too high up

- [ ] Emoji too large

- [ ] Gutters too big, text should not wrap to 3rd line

- [ ] Corner radius on button

- [ ] Gradient colors

Emoji ID screen fixes:
- [ ] Vertical whitespace between emoji ID and content
- [ ] White background behind emoji ID missing shadow
- [ ] Content in center of screen too high
- [ ] Button corner radius and gradient colors
Face ID screen fixes:
- [ ] Shadow behind graphic is missing
- [ ] Skip button missing
- [ ] Content too high up
- [ ] Button corner radius and gradient colors
- [ ] Hello Friend/checkmark
- [ ] Content too high
- [ ] Make checkmark bigger per Zeplin
Animations
- [ ] The black text on each step is not supposed to fade in, but each line is supposed to appear in/slide in from the bottom per Karim's QA video
- [ ] Emoji wheel is a bit off and has a moment where it stops in the middle, see Karim's QA video
- [ ] Face ID is missing the lottie animation
- [ ] On the "Hello! This is your Tari Wallet" screen the waving animation is a bit off. (We have a lottie file for this).
- [ ] Skip button is missing
Other
- [ ] Notifications authorization screen is missing
- [ ] Face ID behavior
- [ ] Screen should not change to the wave hand emoji screen until AFTER user finishes local authentication. Currently it changes at the same time as the OS' local authentication face ID/touch ID modal appears
- [ ] Screen background is supposed to go dark behind OS local authentication modal
"Hello" screen with waving hand
- [ ] Top part should be higher and sharper corners per designs
- [ ] Background should be dimmed

**Comment by Karim-tari** [comment]
The ring loader should be in dropbox as a video that should loop seamlessly, if the video ends up giving us a tough time I can do a different animation and make sure its "lottie friendly".

The "Hello Friend" is 18px

**Comment by lupugabriel** [comment]
@Karim-tari @talmahaj : the background need to be F6F6F6. this is how it is done in zeplin.

**Comment by lupugabriel** [comment]
![Screenshot 2020-03-13 at 10 10 52](https://user-images.githubusercontent.com/3657507/76611778-f1df9580-6512-11ea-9d88-3582b347524a.jpg)

**Comment by lupugabriel** [comment]
@Karim-tari : the Face ID lottie animation is not working. nothing gets displayed. Can you check that please

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS version 0.1.12 on an iPhone 7.

"Hello Friend" screen no longer shows.


![IMG_0297.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2036bea0-8846-4485-9b28-4fcc7128787c)

![IMG_0298.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/049935d1-6414-4bbc-851b-29fa1d6735ff)

![IMG_0299.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/757f8cf0-a9b8-4db4-9df5-e75dafb9b5f0)

![IMG_0300.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/987e1137-931f-4d76-b12e-3022f3714131)

![IMG_0301.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/32409fe0-685d-49bd-ac9b-17c77f35ce0a)

![IMG_0302.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/729615b0-06b7-44e6-ab88-455e15e85976)

**Comment by Anziskavds** [comment]
@talmahaj I had some issues with this card having old information in the description/comments and old designs attached. Would you mind updating me with the latest and expected information and designs for me to test this card from the correct information and designs, please?

cc @SerhiiShovkoplias @kukabi @Tas4tari

**Comment by talmahaj** [comment]
No worries @Anziskavds I can help on any iPhone X UI stuff until we figure it out. 

I just did the testing on this one and it looks great @SerhiiShovkoplias -- really nice work, @karim-tari will be super happy that the app now looks pixel perfect with his designs
