### ISSUE TITLE
QA: Transaction Detail Page

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#168]
**Reference**

Zeplin screen specs: zpl.io/VqXm665

Comparisons of key screens:
<img width="833" alt="Screen Shot 2020-03-08 at 11 37 47 PM" src="https://user-images.githubusercontent.com/1817246/76188624-dcc2d980-6195-11ea-92b9-c5f61b2e1045.png">

**Tal's Fixes:**

- Spacing, gutters, sizes, and type line height & kerning should be identical to Zeplin file. Pls click each element  and each gutter/whitespace in zeplin to confirm everything is built to spec including asset size, border radius, etc. It's helpful to take screenshots and compare to design to ensure it's pixel perfect.
- If it isn't already, timing and UI should be identical to reference video. (Suggestion: an easy way to test this during development is by hitting play on video at the same time as opening your build locally to make sure it's nearly identical
* Back arrow too close to screen edge
* Top nav section too short and also using different shadow styles from design
* Not enough whitespace above amount, below amount
* Transaction Fee text and icon too big
* Can we have the Tari gem vertically centered with the amount
* Explore reducing the kerning on the amount a bit
* The condensed emoji ID should is a bit off from the design
* When tapping on the condensed emoji Id, it should expand to show the full Emoji ID
* Edit link is not aligned with contact name
- When editing contact name, Remove the confirmation message or make it disappear faster so it doesn’t get in the way of back button. IMO if the return key said “Save” or “Done” we wouldn’t need the confirmation message at all…
- Spacing between form elements/labels does not match Zeplin

**Comment by talmahaj** [comment]
@Jasonvdb one more

**Comment by kukabi** [comment]
From @SerhiiShovkoplias : This issue should've been fixed by #296 - moving to UAT.

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS (iPhone 7).

- Spacing, gutters, sizes, and type line height & kerning should be identical to Zeplin file. Pls click each element and each gutter/whitespace in zeplin to confirm everything is built to spec including asset size, border radius, etc. It's helpful to take screenshots and compare to design to ensure it's pixel perfect. - **Some of this still looks different from the designs. Please see my screenshots below when comparing.**
- Top nav section too short and also using different shadow styles from design - **What is being referred to with "Top nav section"?** @talmahaj 
- Transaction Fee text and icon too big - **Still looks a bit bigger than what it is on the design on Zeplin**
- Edit link is not aligned with the contact name - **Still not aligned with the contact name**
- When editing contact name, Remove the confirmation message or make it disappear faster so it doesn’t get in the way of the back button. IMO if the return key said “Save” or “Done” we wouldn’t need the confirmation message at all… - **Not 100% sure what confirmation message?** @talmahaj 





![IMG_A75E647C9988-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7818c213-32c3-43ad-89b9-0985194c4fd1)

![IMG_DB0B6823D33C-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/cb03e4d0-3192-4de6-b0e0-a50fa63323d5)

![IMG_3D354FA7E7B0-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ce5532c1-3c6b-4838-b735-798363397350)

![IMG_1159A5F2E4DF-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4edbacea-d1da-427e-b52d-e5e63482fdf1)
