### ISSUE TITLE
QA: Transactions List Screen

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#169]
**Reference**

Watch from 4:22 onwards of Karim's QA video (turn on audio, he speaks through it all)  now: https://www.dropbox.com/s/x634sgaij2f3nvu/Feedback-Wallet-Creation.mp4?dl=0

01:38 and 2:53 onwards of reference design video:
https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0

Zeplin screen specs:
zpl.io/aNn9wmv
zpl.io/aNnAgMd

Comparisons of key screens:
![Screen Shot 2020-03-08 at 11.49.11 PM.png](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/bb767b34-bde8-42c3-b5d6-74fb20ed12ae)![Screen Shot 2020-03-08 at 11.55.12 PM.png](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/c9f244ca-7c13-4367-b6b1-077f3983eb79)
![Screen Shot 2020-03-09 at 12.44.00 AM.png](https://images.zenhubusercontent.com/5d361e1d286eff0dc8805d38/e808fa3b-61ef-455d-80fa-5263dc06b050)

**Fixes:**

- Gradient colors look a bit different
- ~~When collapsed, drawer height and border radius is incorrect~~
- Spacing below available balance and amount is incorrect
- Amount should have reduced kerning per Zeplin
- ~~Profile icon is too small and too low~~
- Send Tari button is too high, also need to fix border radius and gradient
- Section names are not left aligned with edge of grey circle
- When expanded, X icon is closer to edge than in design
- ~~Contact name and note font size is too small~~
- Note font color is incorrect
- Padding of box behind each transaction amount is incorrect, should have more space above/below
- Pending section is missing animation
- Whitespace between sections, transactions is incorrect
- When expanded, nav heading font size is incorrect
- ~~Animation: Animation for the amount coming in is a bit weird with the 0.00 sliding over, see Karim's QA video for more details~~
- ~~Animation: Adjusting the timing on how and when the items come in. for example: balance and transition should happen at the same time, 3 seconds later we bring the modal.~~
- ~~Tari Bot: Transaction comes in too quickly, and modal should only come in a couple of seconds after transaction does, pls follow timing in video for now and we can adjust after gathering feedback~~
- Spacing and styles in You've got some Tari modal need to be corrected to match Zeplin

**Comment by talmahaj** [comment]
@Jasonvdb another

**Comment by Anziskavds** [comment]
Tested on iOS and have a few questions and also feedback after testing. @Jasonvdb @talmahaj @Tas4tari 

**Questions:**
- I see there is a comma in the Tari balance(Main balance, the bigger numbers) on Zeplin designs but there is no comma in my current available Tari balance. Should there be a comma or no comma in the balance? 
- The color also looks a bit different from the color on Zeplin. Is the color correct as it is currently?
- My balance is correct but just need to confirm the spacing and if it should have a common or not?
- Should the numbers after the "." (the smaller numbers) in the Tari balance be on the top or bottom of the main Tari balance(the bigger number)? I currently see it is on the bottom and Zeplin shows it on the top of the main Tari balance. Also, should it be a "." or a "," after the bigger numbers and before the smaller numbers? Zeplin shows a "." in the designs and I currently see ",".
- "Note font color is incorrect" - The font color looks correct to me" Please confirm?
- "Pending section is missing animation" - Not sure what you referring to. Please let me know what is referred to?
- "Whitespace between sections, transactions is incorrect" - Whitespaces looks correct to me. Please confirm?
- "Spacing and styles in You've got some Tari modal need to be corrected to match Zeplin" - For some reason, I don't receive the "You got some Tari" window when someone sends me Tari. Is there maybe a reason for this?



![IMG_AB5C3B38B3F3-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/1f9a8e24-9921-44b6-b2a2-07b53a099abb)

**Feedback:**
- The Tari send button looks good to me. It looks the same as what is looks like on the designs on Zeplin.
- "Section names are not left aligned with edge of grey circle" - The alignment still looks off.
- "When expanded, X icon is closer to edge than in design" - The "X" icon looks like it is on the designs.
- "Padding of box behind each transaction amount is incorrect, should have more space above/below" - The padding looks correct as seen from the design on Zeplin.
- "When expanded, nav heading font size is incorrect" - The font size looks smaller than what it is on the designs.



![IMG_AB5C3B38B3F3-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/1f9a8e24-9921-44b6-b2a2-07b53a099abb)

![IMG_56F70E476E97-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e56e5db2-a095-4d89-808e-ecdfb4b2d2ec)

**Comment by Anziskavds** [comment]
@Jasonvdb @talmahaj Any feedback yet for me on my above questions?

**Comment by Jasonvdb** [comment]
Tal can comment on the designs but the number formats will differ depending on the country local the phone is set to. i.e. In the US you'll see periods and in SA we'll see commas

**Comment by Anziskavds** [comment]
@Jasonvdb Thank you for your feedback.

I'll wait for the feedback from @talmahaj then.

cc @Tas4tari

**Comment by Anziskavds** [comment]
Tested on iOS version 0.1.15 on an iPhone 7:

**Tested unsuccessfully**
- When expanded, X icon is closer to edge than in design - Tested unsuccessfully. The "X" looks different from the design. The "X" is placed higher on the screen.
- Note font color is incorrect - Tested unsuccessfully. The color looks darker than what it is on the design.
- Whitespace between sections, transactions is incorrect - Tested unsuccessfully. Whitespace between the transactions looks bigger than what it is on the design.
- When expanded, nav heading font size is incorrect - Tested unsuccessfully. The font looks a little bit bigger than what it does on the design.

**Tested successfully**
- Gradient colors look a bit different - Tested successfully
- Spacing below available balance and amount is incorrect - Tested successfully
- Amount should have reduced kerning per Zeplin - Tested successfully
- Send Tari button is too high, also need to fix border radius and gradient - Tested successfully
- Section names are not left aligned with edge of grey circle - Tested successfully
- Padding of box behind each transaction amount is incorrect, should have more space above/below - Tested successfully

**I'm not sure what is being referred to with:**
- Pending section is missing animation?

Is the below screenshot of "You've got some tXTR!" correct? Design is very different on Zeplin. @talmahaj 

@Jasonvdb @SerhiiShovkoplias @Tas4tari 


![IMG_B5E9FF1B888E-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d186b1c5-b3a4-46cc-8f11-e39470242e9b)

![IMG_5B00D887456A-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e4d5f667-c5f5-4edc-8080-8f0d58e3ed70)

![IMG_4E02CA85BF7C-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8f60aa6a-9aaf-4a40-bd51-fb566ba22ddd)

**Comment by Tas4tari** [comment]
Closing this issue as I have created a new ticket for just the fixes: 
https://github.com/tari-project/wallet-ios/issues/422
