### ISSUE TITLE
WalletCreationViewController.swift presents next VC instead of setting the root VC

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#186]
**Describe the bug**
In WalletCreationViewController.swift we're presenting the HomeViewController which keeps all previous VCs in memory. There is code to fix this below the current implementation, however it seems initializing the HomeViewController from here causes issues on it. Further investigation and testing is required here.

**Comment by Anziskavds** [comment]
Spoken to @Jay and asked him how this need to be tested. He said it's not really testable and there won't be a visual difference. "not really testable, there would be no visual difference"

![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2a14693f-3a18-4c27-b4f8-14f9c9daf824)
