### ISSUE TITLE
Deep links don't navigate correctly when app has been closed

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#195]
**Describe the bug**
If the user swipes the app up to close it completely, then deep links only open the app without passing the URL through.

**To Reproduce**
1. Close the Tari app
2. Tap on a deep link
3. App opens but does not navigate to "Add recipient" view

**Expected behavior**
Even if an app is closed it should still navigate to the add recipient view when opened from a deep link.

**Smartphone (please complete the following information):**
All iPhones using iOS 13

**Additional context**
Currently deep links are handled from the SceneDelegate (as of iOS 13). They might also need to be handled in the AppDelegate.

**Comment by Jasonvdb** [comment]
tari://rincewind/eid/💍📎💦🎀💡💉⛵🚒🙅🌽🧢🐭💅⛺🌍🤪🔋🐴👍🍫🎲👗💪✨💌🏠🔔😂🍰📌👖😷😴

**Comment by Jasonvdb** [comment]
[Deep link](tari://rincewind/eid/💍📎💦🎀💡💉⛵🚒🙅🌽🧢🐭💅⛺🌍🤪🔋🐴👍🍫🎲👗💪✨💌🏠🔔😂🍰📌👖😷😴)

**Comment by Tas4tari** [comment]
Open camera on Iphone(Not within the app)  and scan a QR code, that's a deeplink
