### ISSUE TITLE
Analytics tracking

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#200]

**Comment by Tas4tari** [comment]
Tracked on Matomo, ask Leland for log in for Anziska

**Comment by Anziskavds** [comment]
@Jasonvdb I have access to Matomo now. What exactly should I look for in testing this?

**Comment by Anziskavds** [comment]
Tested successfully. 

![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e4dd1879-e505-4be8-8612-60f494bfbc26)
