### ISSUE TITLE
Add Recipient screen: Continue button not appearing when keyboard is up

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#209]
Expected: When a valid emoji ID is entered (typed, manually pasted, or pasted via banner), the Continue button appears visibly whether or not keyboard is collapsed per the zeplin mockup below. That is, if I open the keyboard back up, I should still see the Continue button above the keyboard instead of the Paste banner.

https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e18a8e8211ac4a90601776f

**Comment by Jasonvdb** [comment]
@talmahaj the way fixing this is as soon as we have a valid emoji ID we swop out the text input field for the same styled emoji ID view. Which causes the keyboard to drop automatically and the continue button to be visible. Hopefully that's ok, it seems to achieve the same affect but if you're not happy with that let me know or reopen the ticket if it's closed.

**Comment by talmahaj** [comment]
@Jasonvdb Sounds good, let's try it out and see how it feels!
