### ISSUE TITLE
Emoji ID behavior tweaks

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#218]
- Please make sure the "Copy" button appears everywhere the emoji ID does including the transaction detail page, EXCEPT in the onboarding flow.
- Naveen request:  "on this "this is your Emoji ID" screen, it should first show your full Emoji ID, and then shrink down to showing the short form version with the button there"

**Comment by Jasonvdb** [comment]
@talmahaj can you clarify point 2 a bit? When this view appears should it start expanded, then shrink, then wait for the user to tap it before expanding again and showing the bottom continue button?

**Comment by talmahaj** [comment]
@Jasonvdb yep!

**Comment by SerhiiShovkoplias** [comment]
@talmahaj i left it as default menu (black background with white text). Because on white background it looks very bad 
<img width="358" alt="Снимок экрана 2020-04-28 в 15 53 43" src="https://user-images.githubusercontent.com/60744748/80489409-74f46800-8968-11ea-9e18-3b7f2d9e6eda.png">
<img width="204" alt="Снимок экрана 2020-04-28 в 15 20 55" src="https://user-images.githubusercontent.com/60744748/80489414-76be2b80-8968-11ea-9d07-ff8f32bb73bd.png">

**Comment by talmahaj** [comment]
Hey @SerhiiShovkoplias ! On the onboarding screen, it would be great if the emoji ID could collapse into the shortened version with a smoother transition. Check out how it's done on the Android app (sorry, I should have sent this last week!): https://drive.google.com/file/d/1RNAY5F8dCeK7kDfh-klFI8BeYjE_zhIF/view

Also, the first bullet in this ticket isn't in the testflight build, so I'm guessing it's still in code review or something?

**Comment by Anziskavds** [comment]
Tested successfully on iOS. I'm not sure how smooth you want the transition @talmahaj but it was quite smooth when I tested it. Would you mind having a look on your side and let me know if the transition is smooth enough as expected?

**Comment by kukabi** [comment]
Hi @talmahaj, @SerhiiShovkoplias is working to make the fixes you mentioned.

**Comment by Anziskavds** [comment]
Tested successfully on iOS(iPhone 7). When the app is installed the Emoji ID can't be copied during onboarding but can be copied everywhere else it appears in the app. During onboarding, the Emoji ID shows in full and only shrinks after a few seconds.

![IMG_5F6B5D97C26D-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c94e344d-84a2-4d40-a1e1-3b5f2e16b99c)

![IMG_227635CEECFB-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4b48d7d6-00da-4b90-94bf-d34e6f6cb4e6)
