### ISSUE TITLE
Strip out non-emoji chars when Emoji ID pasted

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#220]
Naveen: so for example I copied the text of Robin's entire message [including the emoji ID] and pasted it in that field, but I can't delete the "Send me Tari" text that he wrote prior to pasting his EmojiID.

Acceptance Criteria:
- Detect if there is an emoji ID in the pasted text, and auto remove the rest of the non-emoji text
- Follow the same behavior as if the clipboard had a perfect emoji ID: display the banner and the paste button abaove the keyboard

**Comment by Jasonvdb** [comment]
@talmahaj these are the cases I've used in the unit tests for this function, all these texts produce valid emoji IDs. If you think there's any cases I've missed let me know or just test in the app after the next update.

`🐒🐑🍔 | 🔧❌👂 | 🦒💇🔋 | 💥🍷🍺 | 👔😷🐶 | 🧢🤩💥 | 🎾🎲🏀 | 🤠💪👮 | 🤯🎁💉 | 🌞🍉🤷 | 🍦👽🔈`

`copy this: 🐒🐑🍔🔧❌👂🦒💇🔋💥🍷🍺👔😷🐶🧢🤩💥🎾🎲🏀🤠💪👮🤯🎁💉🌞🍉🤷🍦👽🔈 please`

`My emojis are "🐒🐑🍔🔧❌👂🦒💇🔋💥🍷🍺👔😷🐶🧢🤩💥🎾🎲🏀🤠💪👮🤯🎁💉🌞🍉🤷🍦👽🔈"`

`🐒🐑🍔🔧❌👂🦒💇🔋💥🍷🍺👔😷🐶🧢🤩 bla bla bla 💥🎾🎲🏀🤠💪👮🤯🎁💉🌞🍉🤷🍦👽🔈`

`My emojis 🐒🐑🍔🔧❌👂🦒💇🔋💥🍷🍺👔😷🐶 and here are the rest 🧢🤩💥🎾🎲🏀🤠💪👮🤯🎁💉🌞🍉🤷🍦👽🔈`

**Comment by talmahaj** [comment]
Slick!
