### ISSUE TITLE
Change "Pending" to "In Progress"

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#225]
@talmahaj commented on [Tue Mar 31 2020](https://github.com/tari-project/wallet-android/issues/253)

From Mattermost:

What would you think if we used "In Progress" instead of "Pending" for the status of transaction that's been sent but not yet mined? I know "Pending" is common in banking for transactions that haven't posted yet, which is why we originally went with it, but IMO "in progress" is far more explicit to the user as to what the heck that in-between state actually means (and "Pending" in banking has an association with long 1-3 day timeframes, which could be misleading)

Acceptance Criteria:
- "Pending" status in Transactions list now reads "In Progress"
- On Transaction detail screen for any transaction with In Progress state, should read "Payment In Progress" instead of "Pending Payment Sent"

**Comment by Jasonvdb** [comment]
@talmahaj on iOS the current titles of the pending TX detail view are "Payment Received" and "Payment Sent". We can change them to "Payment In Progress" for both but then there would be no distinction between sent/received payments on this view. That alright?

**Comment by talmahaj** [comment]
I think it’s fine. Or maybe we can use Outgoing and Incoming? What do you think?

**Comment by Jasonvdb** [comment]
Actually just realised there's "From" and "To" above the emoji ID. It's subtle but maybe enough?

**Comment by talmahaj** [comment]
@Jasonvdb Please make it read "In Progress" instead of "In Progress Transactions"
