### ISSUE TITLE
Width of text area exceeds emoji ID module

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#226]
As seen in https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e25480fbf82f654ef755062, the width of the emoji ID module is the same width as the text area (25px gutter/margin on each side, I believe).

However, in the live app, there is a much smaller gutter such that the small text exceeds the width of the module.

This should not be the case, and ideally the line break can be the same as it is in the design (so long as it doesn't look weird on devices smaller/larger than iPhone X).

**Comment by kukabi** [comment]
@talmahaj @tas4tari I'm thinking this should've been fixed with the new emoji id module updates, moving to UAT.

**Comment by Anziskavds** [comment]
Tested successfully on iOS (iPhone 7).

![IMG_2377C21243B4-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/696d0dfa-31dc-4116-95c8-80a7dfc6c5ff)
