### ISSUE TITLE
Onboarding interstitial disappears too quickly

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#227]
After I enable notifications, the next screen (https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e25461f90ee876aea1e9bea) appears and disappears so quickly (300 ms maybe?) that I barely have a chance to see it, let alone read it.

At a minimum, can we display it for 2-3 seconds so people can read it before it disappears?

If it's not more than 15 min or so of work, would be great to see a video of it as a normal screen (maybe sliding in from the right?) rather than a up/down drawer thing. Or any other ideas you have to make that transition feel slightly less awkward/clunky.

**Comment by Jasonvdb** [comment]
Yes also felt it was a little quick, mentioned it here on the original issue. I think the 1500ms included the time it took for the transition to the new view. I'll add 2500ms and send a vid.

I wouldn't go with sliding in from the right though, as that's more reserved for child views and the user feels there's a parent view they can navigate back to. While in this case once they've navigated away from the onboarding flow there's no going back.

**Comment by talmahaj** [comment]
@Jasonvdb good point re: child views, play around with it and send a vid to me and Karim once you feel good about it

**Comment by Jasonvdb** [comment]
@talmahaj @karim-tari what do you think of this timing? https://share.getcloudapp.com/YEuAnvy1

**Comment by Karim-tari** [comment]
I think the timing is good. Maybe we remove "You're ready to start exploring" ? to make it easier for the user to read everything on screen?

Initially, this screen was intended to be something the user has control of so they swipe down and then they enter the main wallet experience. Though I understand there was feedback to remove that and I agree, its an extra step we don't really need. I wonder if we combine that success message with the feed screen. So something like:
 "Your wallet setup is complete."
   "We don't see any transaction yet. Hopefully, something happens soon "

I can do a quick mockup in a bit.
