### ISSUE TITLE
Amount screen QA: minor tweaks

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#228]
- Top of screen should show Contact Name instead of Emoji ID when available
- ~~Naveen commented that the Continue button became enabled a bit too slowly after he entered the desired amount. Can we speed that up maybe 50% or so (understanding that it's tied to the transaction fee displaying a bit faster too) and see if that doesn't feel far too fast?~~
- Gem icon is too close to 0/amount #. See desired whitespace between the two: zpl.io/aRdMPPK
- Back arrow carat is too far to the left on this screen and others, see zpl.io/aRdMPPK for desired spacing

I know the digits look different between the design and what's built, but Karim changed this after we put in the dev ticket and is fine with the current implementation for launch.

**Comment by talmahaj** [comment]
@Jasonvdb Karim asked if we could also make the animation and timing for each digit you type appearing the same as it is on Android. It's around the 5:17 mark at https://www.dropbox.com/s/l1vgdqvjoa0wb9y/QA-Android.mp4?dl=0

**Comment by Jasonvdb** [comment]
@talmahaj  Have updated the continue button timing. It'll come in 0.2s after typing your first digit. Feels much better.

**Comment by Tas4tari** [comment]
Tested successfully on Huawei P30 lite, screenshots below:
![Screenshot_20200525_195436_com tari android wallet](https://user-images.githubusercontent.com/50987039/82834610-eff66300-9ec1-11ea-97de-c06786eac6c2.jpg)
![Screenshot_20200525_195549_com tari android wallet](https://user-images.githubusercontent.com/50987039/82834622-fa186180-9ec1-11ea-9cc6-dccf4f036ee0.jpg)

**Comment by Tas4tari** [comment]
Apologies, thought this was Android

**Comment by Anziskavds** [comment]
Tested successfully on iOS (iPhone 7).

![IMG_52312EB420D8-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9bebca5b-a32d-4f6e-811d-c33554b052ee)

![IMG_E19202A2D6FE-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/bab099e8-5de4-4c73-91c3-c09bec002162)
