### ISSUE TITLE
Include pending senders/recipients in Recent Transactions

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#231]
1. I had a pending transaction incoming from Cayle
2. I wanted to send him back some Tari
3. I hit the Send Tari button, and on the Recipient screen I was expecting to see his emoji ID in my Recent Transactions list, but it was not there

**Acceptance Criteria**
Users with which you have pending inbound OR outbound transactions should appear under Recent Transactions

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.12 (iPhone 7).

![IMG_C9C3F6B6F0E5-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/75756b85-6048-4f11-8cff-ea61eded877a)

![IMG_312EA6D80252-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/1532abad-047b-4582-a4ba-bdf84efce4f7)
