### ISSUE TITLE
[Feature] Edge case handling: error messages

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#249]
**User Story**

> When I can't use the app, I want an informative, persistent notification telling me why and what to do next

---

**Acceptance Criteria**

1. If the edge cases in either [row 2, 4, or 5 here](https://docs.google.com/spreadsheets/d/1E5gNJXIl14mE0zeJBTZt5OPj0SHKkQEGXYHeLkXpAXY/edit#gid=0) are true, display persistent modal with [the following copy](https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e26abe8de3d8994256095e8) except instead of "it's not you, it's us," the heading should be "It's not you, it's the network"
2. If the user has inadequate or no connectivity per [row 15 here](https://docs.google.com/spreadsheets/d/1E5gNJXIl14mE0zeJBTZt5OPj0SHKkQEGXYHeLkXpAXY/edit#gid=0) AND either taps the send button or attempts to progress to the next step in a transaction, display a modal with the following copy (that the user can tap outside of to close):
"Can’t connect to the internet"
"Your phone appears to be offline or has a poor connection at the moment. Please try again when you’ve found a stronger signal."

---

**Design**

Design specs: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e26ac2d8a5b6752fe7a0377

-----

**Implementation Notes**

- More details on the wallet edge cases can be found here: https://docs.google.com/spreadsheets/d/1E5gNJXIl14mE0zeJBTZt5OPj0SHKkQEGXYHeLkXpAXY/edit#gid=0

**Comment by talmahaj** [comment]
@Jasonvdb Updated the ticket to reflect our convo with Kutsal the other day

**Comment by Jasonvdb** [comment]
@talmahaj @Tas4tari can we close? I think it's been done. It's possibly the spec changed a little because this issue is like 3 months old 🤷

**Comment by Tas4tari** [comment]
@Jasonvdb Understood, let's mention in stand up and then close
