### ISSUE TITLE
QA: Send Transaction: Error Message: Header should wrap to the second line and not truncate

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#251]
**Description**
When a user does a transaction and the recipient is Offline, the user receives an error message with the header truncated.
The header for the error message should wrap to the second line and not truncate.
![IMG_4367 (1)](https://user-images.githubusercontent.com/50987039/78553143-17f21000-7809-11ea-84cb-307f143459e0.PNG)

**Comment by talmahaj** [comment]
Not relevant anymore with store and forward

**Comment by Jasonvdb** [comment]
@talmahaj going to reopen as I reminder to fix for possible future error titles that are a bit long for small devices. Sure it'll happen again at some point

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS. A transaction sent to another user without them having any internet connection(Being offline) without an error message.

It's the "QA" transaction on the screenshot. 


![IMG_69E0E9FDCF67-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c87f7fb2-4412-4215-99c3-68196b38f708)

![IMG_18E7158194AE-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/3986d6f8-6183-4943-8626-96fd0f60dbd2)

**Comment by Tas4tari** [comment]
@Jasonvdb Are we supposed to receive the Offline error now that we have Store and forward?

**Comment by Jasonvdb** [comment]
The error message hasn't changed yet I just reopened the closed issue and didn't see it was still in UAT

**Comment by kukabi** [comment]
@Tas4tari We don't have this error anymore in the app, let's please close the issue - moving to UAT.

**Comment by Anziskavds** [comment]
@Jasonvdb and @kukabi I got a bit confused as I read the comments, should there be the error message or not? 

cc @Tas4tari

**Comment by kukabi** [comment]
@Anziskavds i'm not sure which version you're running, but you shouldn't be seeing this message from iOS v0.1.12 onwards.

**Comment by Anziskavds** [comment]
@kukabi This is my current iOS version and I just installed it from the app store.

 ![IMG_1E68FE915113-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/cda677f7-1f7b-447e-8315-e3aefb864592)

**Comment by Anziskavds** [comment]
Closing the card off. Looks like all the error messages received this far wraps to a second line and don't truncate.

cc @Tas4tari
