### ISSUE TITLE
QA: User is unable to send less than 1 Tari

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#256]
**Describe the bug**
What happened? (Crash/strange behavior)

Strange behavior: cannot send less than 1 tari. 

Example: a user can send 1.5, 1.25, 3.15 but cannot send .25 tari

What did you expect to happen?

Expected to be able to send a transaction for  <1 tari. If that’s not possible, maybe include a disclaimer that transactions have to be >1 tari.

**Device Information**
Network: rincewind
Phone: iPhone 7 Plus
iOS: 13.1.3
App version: 0.1.0
App build: 54

[current-log-2020-04-07_20-22-18.txt](https://github.com/tari-project/wallet-ios/files/4449038/current-log-2020-04-07_20-22-18.txt)

**Comment by Anziskavds** [comment]
Tested successfully. I was able to successfully send 0.25 Tari from iOS.
![image](https://user-images.githubusercontent.com/50451670/80496029-f1874680-8968-11ea-9e1f-9fefa48fb020.png)
