### ISSUE TITLE
QA: Text above QR Code does not wrap and cuts off

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#257]
**Describe the bug**
Text above the QR code does not wrap and cuts off at line 1

**Device Information**
Network: rincewind
Phone: iPhone 7 Plus
iOS: 13.1.3
App version: 0.1.0
App build: 54

[current-log-2020-04-07_20-22-18.txt](https://github.com/tari-project/wallet-ios/files/4449054/current-log-2020-04-07_20-22-18.txt)

![image0](https://user-images.githubusercontent.com/50987039/78759397-dafc5980-797f-11ea-84c8-ba4a20c49a43.png)

**Comment by Anziskavds** [comment]
Tested successfully on iOS. 

![IMG_D8EF86FC290E-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/bb69f460-4430-43ce-aae3-fb75e8df1bef)
