### ISSUE TITLE
[Feature] Store & Forward UX

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#264]
See [parent](https://github.com/tari-project/tari/issues/1694)

**Comment by talmahaj** [comment]
@Jasonvdb Just noting here this is our top pri now, thx!

**Comment by talmahaj** [comment]
@Jasonvdb  This looks seriously amazing so far in the build! I think it works super well, and definitely held my attention while it took a few seconds for my transactions to update.

Two small things:
Assuming you just haven't gotten to this yet, but pull to refresh doesn't work yet.
Also the status bar disappearing after "You are up to date!" appears may be a bit too jarring/fast, not sure if you've gotten to that transition yet though.

**Comment by talmahaj** [comment]
Also @Jasonvdb when the new status bar comes in once you foreground the app, can it do so more slowly to match Karim's video? Thanks!

**Comment by Jasonvdb** [comment]
@talmahaj I did get pull to refresh working, however it interferes with the sliding up of that panel to view txs in full screem :( So right now it's either pull to refresh or allow fill screen txs... I need to dive deeper into a proper solution still. That current panel component might need to be replaced first.

**Comment by Jasonvdb** [comment]
@Anziskavds I'm moving this to UAT, but it's actually been in production for a while. So just keep in mind the end result is likely to be different to this original spec and you have tested this a bunch of times 🤷

**Comment by Anziskavds** [comment]
@Tas4tari As per @Jasonvdb above comment, what do you suggest we do with this ticket? I had a look at it again on version 0.3.0(113) Testflight build and some of the specs are different than the original specs added on here?

**Comment by Tas4tari** [comment]
@Anziskavds Do you have a list of what's different? But let's discuss in stand up

**Comment by Anziskavds** [comment]
@Tas4tari Yes I do, the green is still the same and the red no longer shows. Okay, no problem. Let's discuss in stand up. 

![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/33de246b-50fd-48a0-aab1-878d477c316c)

![IMG_0620.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/61fdc812-f7fb-4fc7-a6b2-e53bac60d1f9)

![IMG_0619.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8fe49a59-1b12-430e-9321-f6b72484f263)

![IMG_0618.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/593f40ea-5e87-4878-a157-cfcfe2084bcc)
