### ISSUE TITLE
Copy update on store modal

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#270]
The copy on the store modal needs to be updated as follows:

Heading: "Spend testnet Tari on real (exclusive) stuff"

"Check out TTL (Testnet Tari Limited) to spend your “hard-earned” testnet Tari on exclusive, one-of-a-kind stuff produced by the team at Tari Labs. Enjoy!"

Buttons:
"Visit the TTL Store"
"I’ll check it out later"

**Comment by talmahaj** [comment]
@Jasonvdb pls fix this one quickly today before diving back into store and forward, thanks!

**Comment by Jasonvdb** [comment]
@talmahaj previously `exclusive items` was bold, do you want any part of the new copy to be bold?

**Comment by talmahaj** [comment]
@Jasonvdb sorry I missed this, would it fit on one line if it read "Spend testnet Tari on exclusive stuff" instead? This way we can bold the "exclusive stuff" too. Otherwise looks great.

**Comment by Jasonvdb** [comment]
Yeah much better. Will put this in the next PR if you're happy with that copy
![Simulator Screen Shot - iPhone 11 - 2020-04-21 at 11 09 22](https://user-images.githubusercontent.com/5300488/79847838-92ea2780-83c0-11ea-8b55-8ae41e06dc56.png)

**Comment by Anziskavds** [comment]
Tested on iOS the wording is a bit different. Please confirm if this is correct? @talmahaj @Tas4tari 

![IMG_9F9265EB17DB-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9d9cf1f0-ddc1-42e5-961b-19b6e06ce155)

**Comment by talmahaj** [comment]
It's good as is, thanks!

**Comment by Anziskavds** [comment]
Thanks @talmahaj for the feedback. Tested successfully on iOS.
