### ISSUE TITLE
In Progress transaction animation freezes when app brought back to foreground

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#271]
From Robin: I'm noticing that the new progress bar for transactions, thing thing that goes back and forth, stops working when you leave the app and come back, it just sticks. Just wanted to make sure you know about that.

I was able to reproduce this on my iPhone too by backgrounding the app and then bringing it back to the foreground.

A few times when I did so, the app crashed instead when I tried to bring it back to the foreground. Sent logs via bug reporting feature.

**Comment by Jasonvdb** [comment]
Lottie animation that gets killed when entering the background should be an easy fix. But the crash is caused by a bug in the current tor lib, that's a little trickier to fix.

**Comment by talmahaj** [comment]
looks good!
