### ISSUE TITLE
Update "transaction in progress" animation that appears once sender initiates transaction

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#272]
See [parent](https://github.com/tari-project/tari/issues/1707)

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.12 (iPhone 7).

![IMG_0305.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/0117cb1a-96c3-4b2b-bf9b-0c9a4eaeb737)

![IMG_0306.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/16663ee6-c597-4e4f-bfbd-5911583b51be)

![IMG_0308.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/23562865-9817-48f1-b443-fda33f439746)
