### ISSUE TITLE
Allow bugs to be shared via other apps if mail fails to construct

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#285]
![IMG_3569.PNG](https://images.zenhubusercontent.com/5ce2547f6eb508477b329ac7/bc1df200-7c8c-4a7f-9a9a-03730eae0607)

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1. 14 on an iPhone 7.


![IMG_153EA71C918B-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2902f068-d9fb-4636-8db1-1a37aa4ab16b)
