### ISSUE TITLE
QA: Transaction List screen: Transaction amount is cut off + emoji ID has inconsistent # of chars

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#286]
**Describe the bug**
1. On the Transaction list screen, the transaction amount appears cut off when there is a long note that has been added. User found once this transaction moved to the bottom of the transaction list, the amount thereafter appears normally.  Both screenshots attached below

2. Emoji ID should only ever show the first 3 and last 3 emojis with the ... in gray like elsewhere in the app. It should never show 4 or more from the beginning or end.

![IMG_3567](https://user-images.githubusercontent.com/50987039/79772796-d301c980-8330-11ea-8868-3ba17b8447a1.PNG)
![IMG_3571](https://user-images.githubusercontent.com/50987039/79772978-1825fb80-8331-11ea-901e-3c13b284f19c.PNG)

**Comment by Anziskavds** [comment]
Tested successfully on iOS.

![IMG_49F8B2B6683F-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5b033ee2-21b1-42bb-b575-f387655e43ca)
