### ISSUE TITLE
QA: Back button on the Transaction Details screen should be aligned the same as the Close button on the Transactions list screen

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#287]
**Describe the bug**
The back button is too close to the side of the screen in iOS. Placement should match the close button
Device: Iphone X
![IMG_3572](https://user-images.githubusercontent.com/50987039/79773688-0b55d780-8332-11ea-802d-1f1265436e51.PNG)

![IMG_3573](https://user-images.githubusercontent.com/50987039/79773621-f7aa7100-8331-11ea-9ce3-334554986ed1.PNG)

**Comment by Anziskavds** [comment]
Tested successfully on iOS. The back button on the Transaction Detail screen aligns with the back button on the Transactions list screen.  

![IMG_D3CA67DA3C65-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/6a9053e1-ba2d-4fa1-8fef-eab8606c2ddf)

![IMG_996673946551-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b209ed36-004e-4677-bbbf-a3178b9a6415)
