### ISSUE TITLE
Change legal links on app splash screen

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#288]
Change the URLs on the app splash screen to the following:

https://www.tari.com/privacy_policy/
https://www.tari.com/user_agreement/

**Comment by Anziskavds** [comment]
Tested successfully on a iPhone 7

**Comment by Anziskavds** [comment]
![IMG_35AC3A4577F9-1](https://user-images.githubusercontent.com/50451670/80484723-7cac1080-8958-11ea-977e-da700b8af882.jpeg)

**Comment by Anziskavds** [comment]
![IMG_777EFFD4C35A-1](https://user-images.githubusercontent.com/50451670/80484924-ce549b00-8958-11ea-859b-cda30be73762.jpeg)

**Comment by Anziskavds** [comment]
![IMG_9E5A52941583-1](https://user-images.githubusercontent.com/50451670/80485116-1e336200-8959-11ea-9d4d-0260687945d5.jpeg)
