### ISSUE TITLE
Ability to remove sender name

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#289]
@talmahaj commented on [Mon Apr 20 2020](https://github.com/tari-project/wallet-android/issues/287)

We should probably have the option to remove a contact name and revert to showing the emoji ID (incase you entered a wrong name and don't know the sender) currently it doesnt let you remove the name you assigned to a transaction.

**Comment by Anziskavds** [comment]
Tested successfully from iOS.

![IMG_7E03A9E590E3-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/121cf193-2959-4d38-9027-7b56f8bd6eb9)

![IMG_DBEC7BC3C7AD-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c839ee3f-0b91-4d4f-86fc-b3ae7f008839)

![IMG_B92BEBA40227-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/01598d0c-87f6-425f-b609-d828c35f7b89)

![IMG_30CC725946E4-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b42866c9-71e0-4214-bc23-e57f53d555e8)

![IMG_6F84A413A70E-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/59cb2a37-9d06-46b7-a32b-463edb23555c)
