### ISSUE TITLE
Only expire pending transactions once the wallet has successfully synced

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#292]

**Comment by Tas4tari** [comment]
To test:
Send a transaction to a recipient, delete the app - recipient should see the transaction stay for 72 hours, once 72 hours have elapsed confirm the transaction is removed from the In Progress section (should disappear completely)

**Comment by Anziskavds** [comment]
Busy testing. I have sent a transaction to my iOS device, I'm deleting the app from my Android device. I'll have a look again Wednesday 6 May 13:15.

**Comment by Anziskavds** [comment]
It has been 72 hours now and I can still see the transaction on my wallet. Tested unsuccessfully.

![IMG_C84CCEDA2A7A-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c9428d73-533d-4d2f-8abe-18fe03bf1791)

**Comment by Anziskavds** [comment]
I need to retest this card. It wasn't mentioned in the comments what exactly the status of the transaction should be before deleting the app and I tested on the incorrect status.

**Comment by Anziskavds** [comment]
Testing in progress. Need to check again Saturday at 16:00

**Comment by Anziskavds** [comment]
Tested on iOS and the transaction has expired as expected. Tested successfully.
