### ISSUE TITLE
Disable swipe nav feature on Transaction Note screen

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#300]
User feedback: "gonna put this out there... i love the swipe and think it's dope... but the last three times I tried to swipe the button, I swiped back to the previous page by accident and had to re-type my message   
my fellow sausage fingers out there are going to struggle"

Jay's response: "yeah I've done this, thinking I need to disable that swipe nav feature on this view only"

So yeah, pls disable swiping to navigate on the Add Note screen :)

**Comment by Tas4tari** [comment]
Another logged from Jessi:
Slider seems to take a little bit of finesse to send. Don’t slide enough and it won’t send, slide too hard and it take you back to the previous screen. Took a few tries to get it to send

**Comment by Anziskavds** [comment]
Tested successfully on iOS. I was able to swipe without going back to the previous page. I also had this issue before but it is fixed now.
