### ISSUE TITLE
[Feature] See cancelled and expired transactions in tx list #1744

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#301]
@talmahaj commented on [Tue Apr 21 2020](https://github.com/tari-project/tari/issues/1744)

**Comment by Anziskavds** [comment]
Tested successfully on iOS (iPhone 7) TestFlight version 0.1.12.

 ![IMG_3CF20F720D6A-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/05e047a9-64fb-4624-94c8-427036f47c0d)

![IMG_D2EE8D8B4C0D-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4677f3e4-184c-4ade-bf42-43cb65684851)
