### ISSUE TITLE
[Feature] Ability to cancel transaction

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#302]
@talmahaj commented on [Tue Apr 21 2020](https://github.com/tari-project/tari/issues/1743)

**Comment by talmahaj** [comment]
@Jasonvdb @SerhiiShovkoplias Let's make sure that the real estate added by the Cancel button doesn't lead to the keyboard covering up the input field again since I know we just fixed it

**Comment by Anziskavds** [comment]
Tested successfully on iOS.

![IMG_FAABA43EC5C6-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f279234b-4710-4bc2-894e-86dbde7714bb)
