### ISSUE TITLE
Copy Change: Change copy for "Hold your horses!" error message that displays when a user has transactions in progress and cannot send another

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#303]
Change copy to:
"Sorry, you can’t send this much Tari until your previous transaction(s) are complete. Please wait for at least one transaction to complete and then try again."

Please note: Keep the title as is: "Hold your horses!"

Current Copy:
<img width="375" alt="9A66768A-10BC-4B5E-BAC4-34C950EFE02F" src="https://user-images.githubusercontent.com/50987039/79959965-18cfa680-8485-11ea-9aa5-e1a8e0aeacbc.png">

**Comment by Anziskavds** [comment]
Tested successfully from iOS(iPhone 7).

![image](https://user-images.githubusercontent.com/50451670/80499896-cfdc8e00-896d-11ea-8205-722e27a983f7.png)
