### ISSUE TITLE
[Feature] Store &amp;amp; Forward - Addl UX improvements

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#308]
@talmahaj commented on [Thu Apr 23 2020](https://github.com/tari-project/wallet-android/issues/298)

See [parent](https://github.com/tari-project/tari/issues/1750)

**Comment by Tas4tari** [comment]
To test second status:
Sender should send a transaction, close their device and recipient should open their app and view the transaction that is from sender, status on Transaction details screen should display as:"Waiting for sender to complete transaction"

**Comment by Anziskavds** [comment]
Tested successfully on iOS.

![IMG_0215.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/bdd480d6-8936-4312-a412-a6493d3060b1)
