### ISSUE TITLE
TX reminder notifications

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#311]

**Comment by Tas4tari** [comment]
@Jasonvdb Will this be in release 0.1.15?

**Comment by Jasonvdb** [comment]
@Tas4tari yes that's the plan

**Comment by Anziskavds** [comment]
It's a bit difficult to test this because I need to use the app every day for testing. I'll test this Friday(26 June 2020) and try not to open the app over the weekend.

cc @talmahaj @Jasonvdb

**Comment by Anziskavds** [comment]
Testing in progress. I have sent some Tari to the iPhone 7 on 2020/07/03 10:40 from my Android device Samsung S9. I will not be using the iPhone from now until Monday to test if I receive a reminder notification.

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS version 0.2.1 on an iPhone 7. I have sent a transaction on 2020/07/03 and haven't opened the app at all over this period of time. I have checked yesterday and today again and I haven't received any reminder push notification. It has been longer than 48 hours and no reminder notification received. @Jasonvdb 

![IMG_0466.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/1e71c0d5-3b65-4aa1-9565-32aa741fa197)

![IMG_3426DA275A5D-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9bd6a44a-a2a8-46b9-a737-8ad1eeb63e40)

**Comment by Jasonvdb** [comment]
Thanks, I'll take a look today

**Comment by Tas4tari** [comment]
@Jasonvdb Removing this from the v0.2.1 release as it's not working

**Comment by Jasonvdb** [comment]
You can remove the release tag because it's already in production. The problem is not that it's not working though. 
The scheduled reminder notifications was a feature request for when the iOS was unable to auto accept transactions as the user needed to open the app for this to happen. Now the app extension seems to be working well. Only when a TX fails to be auto accepted will the reminder notifications be scheduled. It's difficult for @Anziskavds to test this because it relies on the app extension failing.

**Comment by talmahaj** [comment]
Should we reopen this given Jay’s last comment about it not working?
