### ISSUE TITLE
Change Tari and TestNet Tari across the app and Push Notifications to: "XTR" "tXTR" "testnet XTR"

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#312]
**List where changes are required:**

Let’s create your emoji ID screen:
Change “…send you Tari.” to “…send you testnet XTR”

This is your emoji ID screen:
Change “…send you Tari.” to “…send you tXTR”

Let’s secure your wallet
“Tari wallet” —> “XTR wallet”

First faucet tx modal
“You just got some testnet Tari!” —> “You just got some testnet XTR!”
“…a bit of testnet Tari” —> “a bit of testnet XTR”
“Send Tari” button —> “Send tXTR”

Sending animation
“Sending [amount] Tari” —> “Sending [amount] tXTR”

Store modal
“Spend testnet Tari on…” —> “Spend testnet XTR on…”
“…testnet Tari on exclusive…” -> “…testnet XTR on exclusive…”

TariBot transaction message: #1
“Here’s some testnet Tari!” -> “Here’s some testnet XTR!”

TariBot transaction message: #2
“Here’s more Tari” —> “Here’s more tXTR”
“”Hard-earned” testnet Tari”” —> “”Hard-earned” testnet XTR””

Profile screen
“Share it with others to receive Tari.” —> “Share it with others to receive tXTR”
“To send you Tari” —> “to send you tXTR”

Push notifications:
Every mention of “Tari” —> “XTR” Every mention of “testnet Tari” —> “testnet XTR”

**Comment by Jasonvdb** [comment]
@talmahaj Some places missed where I also went ahead and updated:
- `Sorry, you cannot send tXTR to yourself`
- `Scan a Tari QR code to send tXTR to the recipient.`
- Action button (not CTA modal) on home screen `Send tXTR`
- Long press on app icon from home screen `Send tXTR`

Please let me know if any of those are ones I should not have updated ☝️

**Comment by Jasonvdb** [comment]
@talmahaj this is all config based so we've got the display name "testnet XTR" and the ticker "tXTR" and every reference to "Tari" as money now uses one of those 2 options. 

The one piece of copy to change that isn't consistent with the others is "XTR wallet". XTR refers to the mainnet currency so maybe that's misleading? I used "tXTR wallet" instead but if I'm wrong let me know and I'll change it back?

**Comment by talmahaj** [comment]
> @talmahaj this is all config based so we've got the display name "testnet XTR" and the ticker "tXTR" and every reference to "Tari" as money now uses one of those 2 options.
> 
> The one piece of copy to change that isn't consistent with the others is "XTR wallet". XTR refers to the mainnet currency so maybe that's misleading? I used "tXTR wallet" instead but if I'm wrong let me know and I'll change it back?

Per our call today this is totally fine!

**Comment by talmahaj** [comment]
Small fixes already mentioned on MM:

- In the store modal, word capitalization should be "The TTL Store," and the word "The" before "Store" is missing
- In profile screen, the word "Transacting" somehow lost the "T" in front

**Comment by Anziskavds** [comment]
![IMG_CAF1F9FF5BA2-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/67495fbd-9078-4e2f-ab47-4d01436f45c6)

![IMG_0244F3477607-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/fed51869-d91f-4e44-9b7e-0fcefc18ace5)

![IMG_0193.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/efc3d862-9f3a-4a74-bf2a-c6913238033a)

![IMG_0190.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2f5c93a2-2e12-49ea-8892-5fbc72b5cc92)

**Comment by Anziskavds** [comment]
![IMG_68B105860AF1-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a0f1ca36-307c-4fc5-af48-bf50f7534a25)

![IMG_0188.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/75c4d2db-3baf-40f6-828b-442da8c55282)

![IMG_0187.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8f41735c-728a-44f8-86bb-a0d2bffbae5a)

![IMG_0186.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/bff44222-f7ce-4b52-9228-afbf29539f03)

![IMG_0185.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c0ccf8b1-64ba-428b-85e6-1ca167b271d1)

![IMG_0182.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d6035676-57db-4175-8525-a17d81a59b32)

![IMG_0181.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e1a508dc-8f84-48db-9c8e-93b37b3c0986)

![IMG_0178.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a17e89a1-524a-4682-bb51-407f1c0c64be)

![IMG_E1C071C384FC-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f75cb06a-038e-462d-a3eb-98341fbf8348)

**Comment by talmahaj** [comment]
@Anziskavds @Tas4tari can we close?

**Comment by Tas4tari** [comment]
@talmahaj:
@Anziskavds Needs to confirm the following before closing:- 
In the second faucet transaction, change the "S" in "Store icon" to be lowercase since - Tested unsuccessfully @Jasonvdb

**Comment by Anziskavds** [comment]
Tested successfully on iOS.

![IMG_F4FA44EFDA62-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ea82ea5a-8d42-4875-b5cb-99c5021fede8)
