### ISSUE TITLE
Create your emoji ID: Emoji ID Tooltip: ToolTip "Tap to see Emoji ID " is not tappable

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#313]
Fix the Emoji ID tooltip as it is currently not tappable. 

Ensure tooltip is tappable and displays the user's full Emoji ID when tapped by a user

**Comment by Anziskavds** [comment]
Tested successfully on iOS.

![IMG_0179.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/293a9e06-5380-47fd-a2aa-eacfe6a99f87)![IMG_0181.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ff17e320-80b6-43c6-b66f-f449b62fc7b5)
