### ISSUE TITLE
Transaction list screen: Status Animation: Remove the behavior of the "checking for updates" banner appearing with each base node sync failure so it only appears whenever you open/foreground the app OR whenever you manually pull to refresh

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#314]
Remove the behavior of the "checking for updates" banner appearing with each base node sync failure so it only appears whenever you open/foreground the app OR whenever you manually pull to refresh

**Comment by Anziskavds** [comment]
Tested successfully on iOS. The "checking for updates" banner only shows when you open/foreground the app.
