### ISSUE TITLE
QA: Push Notifications: User receives notification that they've been sent Tari, however when they open the App they don't see any transactions

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#316]
**Description**
I got a push notification that someone sent me tari, but when I opened the wallet I don’t see any new transactions. There seems to be a delay of about 20 + mins from the time I get the push notification to when I actually see the new transactions in my account 

**What did you expect**
When I receive a push to alert me that someone sent me tari, I expect to see a transaction that corresponds with this notification 

**Logged by**
Jessi 

**Device Details**
Network: rincewind
Phone: iPhone 7 Plus
iOS: 13.1.3
App version: 0.1.0
App build: 62
Reachability: WiFi ✅
Base node: Pending first sync ⌛
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

[2020-04-23_12-00-23-bug-report.zip](https://github.com/tari-project/wallet-ios/files/4527507/2020-04-23_12-00-23-bug-report.zip)

**Comment by Anziskavds** [comment]
Tested successfully on iOS. When I received the push notification and I clicked on open, it redirected me to the  Tari App Transaction Detail screen.

![IMG_453354F34CEF-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/07824fe8-089d-43f9-8e62-51ccee955019)

![IMG_70C6329CF414-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8aedb0b5-e0ee-4355-a9d7-1d4aad680ab8)
