### ISSUE TITLE
Add background shadow to notification and local auth opt-in graphics

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#323]
In onboarding flow, the graphics for the Touch ID and Face ID are missing the shadow that's in the specs:
https://camo.githubusercontent.com/fdc6f856f4350a7decb4cacb048ab07b22282817/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564333631653164323836656666306463383830356433382f66306332663966362d303430302d346132662d616663612d613632303566643631326265

Shadow specs in Zeplin: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5e2548927b386169804234a7

**Comment by Jasonvdb** [comment]
@SerhiiShovkoplias please also see why the FaceID lottie animation is a little off centre to the right

**Comment by Anziskavds** [comment]
Tested successfully on iOS.

![IMG_76BF4F1C184D-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4fcb12ab-621f-4d52-a185-ccf13b1def46)
