### ISSUE TITLE
App extensions!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#324]
WOOHOO

**Comment by Tas4tari** [comment]
Background refreshing functionality:
When app is in the background and user receives a transaction, does the transaction confirm

**Comment by Anziskavds** [comment]
Having issues with the app. It keeps on crashing. I'll try again tomorrow. I already have let @Jasonvdb know.[Uploading... IMG_0359.PNG ]

**Comment by Anziskavds** [comment]
Tested on iOS version 0.1.14 and I have received the below screen. I have sent a transaction from my android device to my iOS device while the app was running in the background. This is the screen I received. Is this the correct status it should show? @Jasonvdb 

![Screenshot_20200602-113313_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7b5a79b4-9a9d-43d4-b5db-f473089fb3e9)

**Comment by Jasonvdb** [comment]
No the status should be "Completing final processing…" and it can take about 30s to a minute. It's not always reliable but you can cancel the tx and retry

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.14. Tested on and iPhone 7 and sent the transaction from a Samsung S9.

![Screenshot_20200602-121534_Tari Aurora.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5d17e2e7-68f3-4315-a4c3-7839d6476a43)

![IMG_9CF8512C946B-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/3687b5d8-1e50-4b29-837e-f73a2041075b)
