### ISSUE TITLE
Onboarding flow timing between enabling notifs and "try sending tari" modal

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#325]
All the steps after enabling notifications ("explore your wallet" prompt -> list empty state -> first faucet transaction -> the modal encouraging the user to send Tari) happen a bit too fast for the user to understand what's going on.

Check out the timing on Android, and see if we can implement something similar on iOS to give the user more time to digest what's going on at each step.

**Comment by Anziskavds** [comment]
Tested on iOS (iPhone 7) and the timing between the different screens seems much similar to Android and it wasn't happening fast while I was testing.
