### ISSUE TITLE
App crashes when you tap number buttons too quickly on add amount view

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#327]
@crypt0ginge just subscribing you to this issue for updates so I don't have to

**Comment by Anziskavds** [comment]
Tested successfully on iOS. I was able to add a few numbers, in less than 5 seconds without the app crashing.

![IMG_BF112082AB5B-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/78e3a3a2-1c6c-4b89-afb0-f95534deb9a7)
