### ISSUE TITLE
QA: Transaction Details Screen: Entering Contact Name: User is unable to as keyboard covers the input field

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#330]
**Description**
When adding a contact name my keyboard covers the text input so I can't see what I'm typing 

**Device Details**
iPhone 8
iOS 13.3.1 

**App version**
Tari aurora 0.1.0 (64)

**More Notes**
Keyboard is Gboard (not sure if other keyboards do the same)

**Comment by Tas4tari** [comment]
![IMG_9838](https://user-images.githubusercontent.com/50987039/80471182-592a9b00-8943-11ea-9850-48459f0f94ae.PNG)

**Comment by Tas4tari** [comment]
As per Jessi this also happens on an iPhone 7 plus
@Jasonvdb  See comment below
**What happened? (Crash/strange behavior)**
When adding a contact name:
If the transaction is still in progress, The phone keyboard hides the contact name line when adding contact name 
**What did you expect to**
Expect to be able to see the entry field as you add contact info 

**Device Details**
Network: rincewind
Phone: iPhone 7 Plus
iOS: 13.4.1
App version: 0.1.0
App build: 64
Reachability: WiFi ✅
Base node: Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Comment by SerhiiShovkoplias** [comment]
This issue should be solved as part of another task. [PR](https://github.com/tari-project/wallet-ios/pull/341)

**Comment by Anziskavds** [comment]
Tested successfully on iOS.

![IMG_353B7D439F3F-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/11cb495d-9642-420d-aa85-23bd5c3516d9)
