### ISSUE TITLE
QA: Transaction Details screen: When user selects to see the full Emoji ID in the "From" section, it overlaps the text

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#331]
**Description**
When I haven't added the contact name yet, and click to see the whole emoji ID the emojis overlap the text 

**Device Details**
iPhone 8
iOS 13.3.1

**App version**
Tari aurora 0.1.0 (64)

**Comment by Tas4tari** [comment]
![IMG_9833](https://user-images.githubusercontent.com/50987039/80471619-f38ade80-8943-11ea-85ac-24c4eb6094e5.PNG)

**Comment by Anziskavds** [comment]
Tested successfully on iOS. I was able to see the full emoji ID without overlapping the text.

![IMG_3B70D2584F63-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f81c4c0f-0d78-4d4c-b78d-16fcdf3570c5)

![IMG_0D541A93ECE5-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ea0995a0-e477-4da2-a3e6-2bf8b9165b52)

![IMG_98AC3FA8C0BD-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9c7c6c98-9ee9-4422-ba02-2af5d5d2ddf2)

![IMG_93DC0E696B6E-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b3eb7560-0347-4eb0-b4c5-d4ea1cc25932)
