### ISSUE TITLE
No limit on chars for contact names

### ISSUE THREAD

**Issue by crypt0ginge** [tari-project/wallet-ios#336]
**Describe the bug**
There's no limit on the number of chars required when editing contact names.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select 'Send tXTR'
2. Select 'Edit'
3. Select 'Contact Name'
4. Add chars for days

**Comment by Jasonvdb** [comment]
@SerhiiShovkoplias let's set the limit to 60 chars for now, can always adjust later

**Comment by Anziskavds** [comment]
I am limited on 40 chars? What is the correct amount of limited chars?
 @Jasonvdb @talmahaj 

![IMG_B4EBD1FF96B8-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/6ea10de7-8200-4f28-a39a-bcc54e81261f)

**Comment by Jasonvdb** [comment]
@Anziskavds yup 40 chars is fine according to @crypt0ginge

**Comment by Anziskavds** [comment]
Thanks @Jasonvdb. Tested successfully on iOS.

![IMG_B4EBD1FF96B8-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b8c2bade-6792-41f7-9fd1-c6872bdf42c2)
