### ISSUE TITLE
Launch QA: App crashed with Enable Notifications screen in background

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#339]
**Description**
App crashed with enable notifications screen in the background

**Additional Information from Reporter:**
وЮ ○三 🐙＼(ₑ₂̑Ꮘↂͩ ₂̑ₑ), [Apr 28, 2020 at 8:59:19 PM]:
only funny thing i did was not allow notifs when i first set it up
yea seems like it was just during that initial run of the app**Expected behavior**

**Reporter Telegram username:**
@pussinboots

**Smartphone:**
IOS Device: iPhone 8 latest
OS version: 13.3.1

**Screenshots**
![photo_2020-04-29 12 14 45](https://user-images.githubusercontent.com/50987039/80585345-76c73580-8a13-11ea-98b9-abbdfed13928.jpeg)
![photo_2020-04-29 12 14 39](https://user-images.githubusercontent.com/50987039/80585376-85ade800-8a13-11ea-8360-2a52f7cbff8d.jpeg)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.3.0(115) on an iPhone 7. I was unable to get these screens and the crash as mentioned above. There is no option to go to the wallet without selecting the allow or not allow button for notifications and also no way to go back to the notification screen when you are on your wallet. When the app was in the background and I went back to the app it opened on the notifications screen again as it was before the app was background without any crashes.

![IMG_0687.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ee02f99e-8275-406e-bbb5-ee7517d18572)

![IMG_DDF5479BAE01-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/77457a86-2bce-4130-9e8c-ed5ff7ec28ae)
