### ISSUE TITLE
Launch QA: Bug Reporting: Multiple tabs open up when user shakes the device

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#346]
**Description**
When shaking phone to open the “report a bug pop up” multiple times the pop up keeps showing up. In order to get out of this I need to press “cancel” as many times as I shook my phone to close all open pages. 

**Expected behavior**
I would expect the report a bug pop up to only show up once. And not open again after another phone shake. 

**Smartphone:**
Network: rincewind
Phone: iPhone XR
iOS: 13.3.1
App version: 0.1.1
App build: 67
Reachability: WiFi ✅
Base node: Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs:**
[2020-04-30_11-51-19-bug-report.zip](https://github.com/tari-project/wallet-ios/files/4571004/2020-04-30_11-51-19-bug-report.zip)

**Reporter:**
Jesse Smith

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS version 0.1.12 (iPhone 7). I shook the device 5 times and the window opened 5 times. After I clicked on cancel, I needed to click on cancel again another 4 times to close all the windows. @kukabi

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.14 on an iPhone 7. I have shaken the device 5 times and the "Report a bug" tab only opened once(Only clicked on cancel once and the tabs closed).

![IMG_2C33621353BE-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/28bcbf9b-368c-4dfb-bfc3-f018054a2281)

![IMG_D6AA88A91E55-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a45042be-94d4-4adb-9f7c-b6bb5c589844)
