### ISSUE TITLE
Long press "Copy" button on emoji ID to copy pubkey

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#353]
@talmahaj commented on [Wed May 06 2020](https://github.com/tari-project/wallet-android/issues/335)

Great idea by Jay for a bandaid solution to the problem where the Emoji ID renders as images instead of emoji when pasted in certain apps: 

- When user **long presses** on the copy button, instead of copying the emoji ID, it should copy the alphanumeric pubkey into the clipboard. (When the user's recipient adds it to clipboard, it will display as an emoji ID again in their app)

In the future, we'll have a settings screen where pubkeys will be more explicit/discoverable, but in the meantime we can at least share this feature with users on telegram who are struggling

**Comment by Anziskavds** [comment]
Tested successfully on iOS.

![IMG_DE467851EBB1-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/515fec4d-ab02-40c8-9b4c-082279fb23cf)

![IMG_894FE8DDED7E-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5d03fcf1-1a10-4e74-922b-f0a85016825b)

![IMG_9F9C76638713-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a3e64ce0-253c-4e21-af3e-89da641ea4f3)
