### ISSUE TITLE
Wallet info layout is broken on a 4-inch screen.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#354]
**Describe the bug**
Wallet info screen layout breaks on an iPhone SE, a supported device.

**To Reproduce**
View the screen on an iPhone SE device or emulator.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: 13.3.1

![IMG_8211](https://user-images.githubusercontent.com/2969501/81146391-da57e280-8f80-11ea-9e37-7c2fbc6c24e5.PNG)

**Comment by Tas4tari** [comment]
@kukabi Any feedback with regards to the issue on the iPhone SE

**Comment by kukabi** [comment]
@Tas4tari It's working good, can be closed.
![IMG_8238](https://user-images.githubusercontent.com/2969501/82290172-f317bd80-99ae-11ea-8eb5-b4edbe81c247.PNG)
