### ISSUE TITLE
Navigation bar still visible after returning from Add Recipient screen.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#356]
Navigation bar takes a while to disappear when the user returns to the transaction list from the Add Recipient screen.

**To Reproduce**
1. While on the transaction list, click "Send tXTR".
2. Click on the back button on Add Recipient screen.

**Expected behavior**
Navigation bar should never show in the home screen.

**Screenshots**
![iOSNavBar](https://user-images.githubusercontent.com/2969501/81154619-c1552e80-8f8c-11ea-98c2-6fa65c181d64.gif)

**Smartphone (please complete the following information):**
 - Device: Any supported device.
 - OS: Any supported OS.

**Comment by Anziskavds** [comment]
Tested successfully on iOS (iPhone7).

![IMG_2DD3BA42810B-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7b4b440c-45be-4325-8043-a49862798b40)


![IMG_B18353E4B974-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2303a848-dec4-48c8-90ff-ed7985c271d3)


![IMG_B46642C642C3-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4f93bd70-0e59-4031-bb25-93fe1c43630d)


![IMG_B4D988AAD790-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/53ac8edf-9881-4a67-aac3-5640807342cf)
