### ISSUE TITLE
[Feature] Open TTL Store in in-app browser

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#369]
See [parent](https://github.com/tari-project/tari/issues/1843)

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.14 on an iPhone 7.

![IMG_435016242ECD-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d8bf0262-e7fb-4f08-9ea9-3e2ad9c21087)

![IMG_00300A0C5A5A-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/018435c8-1dfb-4592-845b-50907af645a3)
