### ISSUE TITLE
Pull to Refresh Tweaks

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#370]
- Can the Status Update banner be fixed to the top of the view rather than being dragged down along with the rest of the list, just like it is in Android? This way we don't have the jarring transition once the refresh is triggered where it suddenly appears and the list drops down.

- Maybe it's just me and my small fingers, but it feels like you have to swipe really far down to activate the refresh. Is it possible to shorten this some?

**Comment by kukabi** [comment]
@talmahaj I'll have a look at what we can do to make it the same as Android, starting tomorrow.

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.14 on an iPhone 7.

![IMG_E8C3D1898C7F-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7fbb2425-09cd-477d-a7d7-172fb6305396)
