### ISSUE TITLE
QA: Onboarding flow: Tap to see full emoji ID screen UI is broken

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#375]
**Description**
User downloaded the build from TestFlight and was going through the onboarding flow, when user selected to create their Emoji ID, when the emoji ID is created, on the Tap to see full emoji ID screen the UI displayed with the emoji loading animation overlapping the "This is your emoji ID" screen

**Screenshots**
![IMG_5824](https://user-images.githubusercontent.com/50987039/81891599-228e8a80-95a9-11ea-8818-e6f3aa637c53.PNG)

**Smartphone:**
 iPhone X

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.12 (iPhone 7)

![IMG_0CA6808048A4-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/421e895e-9aca-4c78-9876-4923b8d06645)
