### ISSUE TITLE
User can send transactions when app is completely offline

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#376]
**Describe the bug**
Can send when app is completely offline

**Smartphone :**
Network: rincewind
Phone: iPhone XR
iOS: 13.3.1
App version: 0.1.3
App build: 79
App environment: debug
Reachability: WiFi ✅
Base node: Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs:**
[2020-05-13_10-13-57-bug-report.zip](https://github.com/tari-project/wallet-ios/files/4628062/2020-05-13_10-13-57-bug-report.zip)

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.12 (iPhone 7). I was offline and the transaction didn't send when I tried to initiate a transaction. It stayed on the below screen.![IMG_66E8D9846181-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9350cbc3-bc0c-4851-8f20-3458c43f57d5)
