### ISSUE TITLE
Launch QA: Push Notifications: When user receives a Push Notification and select it, when they go to the wallet their transaction is not displayed

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#384]
**Describe the bug**
Received a push notification that someone sent me tari yesterday afternoon at approx 430pm ct. I’ve been checking my wallet but the transaction still has not posted 

**Expected behavior**
I expected to see txtr in my account when I received the push, or very shortly after 

**Smartphone:**
Network: rincewind
Phone: iPhone 7 Plus
iOS: 13.4.1
App version: 0.1.1
App build: 67
Reachability: WiFi ✅
Base node: Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs:**
[2020-04-30_08-52-14-bug-report.zip](https://github.com/tari-project/wallet-ios/files/4570995/2020-04-30_08-52-14-bug-report.zip)

**Reporter:**
Jessi Pray

**Comment by Tas4tari** [comment]
@Jasonvdb To outline what he needs to do

**Comment by Jasonvdb** [comment]
This is just the behaviour users are expecting but we didn't have support for yet. 
Related to https://github.com/tari-project/wallet-ios/issues/324 and should be in the release right after next.

**Comment by Tas4tari** [comment]
@Jasonvdb Will this be released in v0.1.15?

**Comment by Jasonvdb** [comment]
It should be already live in prod actually, but only if the app extension executed successfully. It mostly will but there can be the occasional instance where it won't. Can probably close this.

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS on an iPhone 7 on version 0.2.0. @Jasonvdb 


![IMG_0400.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2b5b75a3-290f-4221-9321-3141b989fcf5)

![IMG_696A184A2211-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/0ac643ab-3466-4124-84b6-18f16802dccb)

![IMG_86F252E2015E-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/0fdd3b4f-cdc1-42c6-9332-d9bd791b2562)

**Comment by Jasonvdb** [comment]
@Anziskavds can you give more context here about how you tested? Are those 2 pending txs not the ones you were expecting?
This is unfortunately one of those features that's never going to work 100% of the time and you might need to run through a few times. It was released in 0.1.14 though with no changes to it in 0.2.0

**Comment by Anziskavds** [comment]
@Jasonvdb No, it wasn't the two transactions I was expecting. I will retest this and see what it's doing today.

**Comment by Anziskavds** [comment]
Retested on iOS version 0.2.0 on an iPhone 7. I've sent some Tari from my Android device to my iOS device and when I received the push notification I've opened my wallet by clicking on the push notification and the transaction doesn't show on my transaction list. I've done the transaction this morning and still doesn't show on my transaction list screen. @Jasonvdb 

![IMG_0410.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f4de9bdf-59b2-4899-a88b-e2db0e536986)

![IMG_0411.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e86cfe64-ae48-44c2-ba10-ba847dcfccc2)

![IMG_1276CE63BB2C-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/29971694-af75-4053-8ac5-5ef36976a55f)

**Comment by Jasonvdb** [comment]
@Anziskavds you can probably try this again

**Comment by Anziskavds** [comment]
Tested successfully on iOS on an iPhone 7 version 0.2.1.

![IMG_0473.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7bab37d9-f56d-48cc-a7cd-b3e22bbf3767)

![IMG_0474.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/bcbd1e5e-5228-4104-ba60-77786cdf7b27)

**Comment by Jasonvdb** [comment]
Just a note as to what happened here. The scheduled reminder notifications was a feature request for when the iOS was unable to auto accept transactions as the user needed to open the app for this to happen. Now the app extension seems to be working well. Only when a TX fails to be auto accepted will the reminder notifications be scheduled.

**Comment by Tas4tari** [comment]
Received issue via the Bug reports feature on IOS:

**User:**
Giannis Bakopoulos

**What happened:**
I got a notification that I received tXTR. I didn’t send anything to myself and I don’t know if someone actually send me tXTR. I went inside the app but I didn’t receive any new tXTR.

**Device:**
Network: rincewind
Phone: iPhone 11 Pro
iOS: 13.5.1
App version: 0.2.1
App build: 101
App environment: production
Reachability: WiFi ✅
Base node: Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs:**
[2020-07-07_08-08-53-bug-report.zip](https://github.com/tari-project/wallet-ios/files/4885998/2020-07-07_08-08-53-bug-report.zip)

**Comment by Jasonvdb** [comment]
@Tas4tari the iOS app is as good as it's going to get for now regarding this issue. It'll never be 100% solved until the store and forward part is a 100% reliable. I think we can close for iOS because there's not much more I can do?
