### ISSUE TITLE
Remove last of the storyboards and .xib files

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#398]
A while back we made the call to go with all UI and layout in code to avoid messy git conflicts with a larger team. There's still a `Main.storyboard` and `TransactionTableTableViewCell.xib` that needs to be rewritten in code. 

Maybe the `HomeViewController.swift` can also be refactored to put all the UI code in an extension file.

**Comment by kukabi** [comment]
@Jasonvdb I think this one is not testable, shall we close it? @tas4tari

**Comment by Jasonvdb** [comment]
@kukabi yeah, if everything looks the same as before then it's good

**Comment by kukabi** [comment]
OK, @tas4tari you may close this issue if everything is looking ok in general.

**Comment by Anziskavds** [comment]
@Jasonvdb Do you have any steps for me to test this, please?

cc @Tas4tari

**Comment by Anziskavds** [comment]
Spoken to Jay and also as per the above comments Jay said this is a code cleanup and there shouldn't be any visual changes as soon as everything still looks the same this card can be closed.
