### ISSUE TITLE
Copy Change: TDS Screen: Waiting for recipient to accept transaction

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#400]
**Description:**
A number of users have been confused with the status "Waiting for recipient to accept transaction" on the Trans action Details screen.

Change copy to: **Waiting for recipient to come online**

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.14 on an iPhone 7.

![IMG_75DB411C12A9-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/193b23e9-8010-4d11-ae57-09c02a4775a7)
