### ISSUE TITLE
[Feature] Backup & restore wallet: Wallet backup options screen

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#401]
See [parent](https://github.com/tari-project/tari/issues/1906)
02 June 2020: Additional requirement added [here](https://github.com/tari-project/tari/issues/1906)
**The updated requirement:**
- If user taps either method, they should have to locally authenticate (e.g. biometrics) before being allowed to continue (unless no local auth is configured for device)

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.2.0 on an iPhone 7.

![IMG_0445.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/73a1a3f5-226f-4bfd-953f-bcf7a6d040cc)

![IMG_0446.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/657c34eb-d2a5-4e6f-8704-1ae24a0a7a59)

![IMG_0447.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/399d795c-c913-499c-a866-1c3df4ee6d05)

![IMG_0450.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/bf2c541b-32ba-4e82-b895-636881818a9a)

![IMG_0451.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d18270cd-0470-4fd0-966f-64bfc4c9c533)

![IMG_0452.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/93e9eace-3e57-4647-b9d9-0831d01be6ef)

![IMG_0420.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9360c935-1e54-4eb7-bca6-7ef9d57cf7aa)

![IMG_0421.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e6c7aed8-1726-4adc-b2a1-065200198785)

![IMG_0422.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/357b5d09-8d1c-40c1-9807-af88ecfe3047)

![IMG_0423.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8c10f3ee-d4c2-4c16-942b-a7afcb235e4d)
