### ISSUE TITLE
[Feature] Backup & restore wallet: Back up to iCloud/Google Drive

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#404]
See [parent](https://github.com/tari-project/tari/issues/1906)

**Comment by Anziskavds** [comment]
Tested on iOS on version 0.2.0 on an iPhone 7.

**Wallet backup options screen** Tested successfully
**Back up to iCloud/Google Drive** Tested successfully

![IMG_0414.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b170aae1-0eb1-4a97-bf1d-c2f38d8f961a)

![IMG_0415.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/260d72af-3164-4371-8cfa-26b122b88fde)

![IMG_0432.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/18cfed9f-585b-4fb4-a56e-4f0b6138399f)

![IMG_0417.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/01e60a9a-b661-46a9-895c-57f268cd0497)

![IMG_0418.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/67a994a1-4c55-4f77-891d-e4058af12e13)

![IMG_0419.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/befcc75b-8185-4a81-a111-459227ce2895)

![IMG_0420.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4f0ac849-3c37-41a1-b658-c13d0ddb4902)
