### ISSUE TITLE
[Feature] Backup & restore wallet: Settings screen

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#406]
See [parent](https://github.com/tari-project/tari/issues/1906)

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.2.0 on an iPhone 7.

![IMG_0445.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/69756759-4172-473e-9eec-f8f5d49e3eef)

![IMG_0446.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d4500831-dfee-4871-a187-b8124ce81630)

![IMG_0447.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c60710f8-bc1d-43d9-a5c2-822f4ee79e07)

![IMG_0452.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c8a4a48f-2543-4317-91d9-44e5bd5f2772)

![IMG_0441.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/bf86f336-1c5c-48de-9219-82b4c44a5e07)

![IMG_0442.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2d87bad4-abf4-45d4-ab1f-1f6427e74e7e)

![IMG_0443.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e8c66d8a-68f3-40cb-8b4c-881e721e0f7d)

![IMG_0444.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7be88bc8-1984-40bf-970b-a0816de8bdbe)

![IMG_98FB65AE37A0-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/6fd47a77-e40b-4d7c-8814-77220a7f4d8c)
