### ISSUE TITLE
[Feature] Backup & restore wallet: Restore wallet flow

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#408]
See [parent](https://github.com/tari-project/tari/issues/1906)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.2.0 on an iPhone 7.

![IMG_0445 2.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2a2fe0f5-4eff-402d-9114-967744fafe05)

![IMG_0455.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7874355b-ea35-40ac-ab60-b38c1d6838fc)

![IMG_0456.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ebf0ebed-6085-4023-88a7-abd66bcfb6c4)

![IMG_0457.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/cbbb6a5f-c362-4739-9f15-9f72b6f7a535)

![IMG_0458.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5b8c9516-557f-4948-8068-270a5c331f11)

![IMG_0459.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/cd0675f8-4a8e-4b0a-8058-5f43b348c410)

![IMG_0460.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/07a69277-bcdc-433e-9af0-dddf230053a9)

![IMG_0461.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/0c9afd18-6262-4c7a-ae2b-1affd8114ae6)

![IMG_0462.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/dc858446-bcd7-4c77-a670-c7b37bd2c11e)

![IMG_0463.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c7d801a4-b0dd-46dc-8e8f-259440a2498b)
