### ISSUE TITLE
[Feature] Backup and restore wallet: UI Interfaces

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#412]
See [parent](https://github.com/tari-project/tari/issues/1906)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.2.0 on an iPhone 7.

![IMG_0439.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b3e27ccc-7ca4-4cee-82b2-330900d25f16)

![IMG_0414 2.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d9916165-f173-4bec-9e51-fea907b6dad5)

![IMG_0415 2.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f6fa650c-2c17-4296-95e7-6b744234d520)

![IMG_0450.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4e568b53-0482-4400-8b6f-b5edf608ce72)

![IMG_0417 2.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7c7a52bf-1cda-4e4f-932e-a5ec0a2fa8d2)

![IMG_0418 2.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/bc639d32-691a-4d01-af78-4745a9c72aba)

![IMG_0419 2.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8e3da215-5545-44d8-a3d5-1a0ed1376fff)

![IMG_0455.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/82e363b0-118b-4a6d-8f05-1d9e38eca23b)

![IMG_0456.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/315c530e-6601-4ea0-a470-3c4dd6446730)

![IMG_0457.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a5f6465f-b8f4-42a1-8ecb-4d2f13b1d243)

![IMG_0458.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c5e4ee2d-937c-441f-843e-324ca4d28dd3)

![IMG_0459.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/bab1bcd3-1870-4b46-b40c-1615fc352b11)

![IMG_0460.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/3761251c-e61e-4b9f-b587-772d9816c5a2)

![IMG_0461.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/966f31b5-6d79-4977-9e70-1d1bc2b4a04f)

![IMG_0462.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/accc54a7-5afa-4c17-b893-15ddd3ba1cad)

![IMG_0463.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/62d6f71e-4bb8-4486-88e7-e9647d3fe7e6)

![IMG_0441.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/cd71ff07-7326-4e46-abb5-a8db76465e53)

![IMG_0442.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4fffba26-3646-4262-acfb-597f67cd8887)

![IMG_0443.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4ecb624b-651c-402e-9ecb-6159e20b900d)

![IMG_0444.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d01b8662-2858-46c6-8145-5f4c9ca9a686)

![IMG_98FB65AE37A0-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d87c9bb6-9e85-448f-8a42-ac63bfdbd3ec)
