### ISSUE TITLE
Emoji ID compatibility error handling

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#416]
Once we release a version of the wallet with a new emoji set, users on that version will not be able to transact with users on prior ones and vice versa. This means we'll need to show an error message for users who try to do so.

Implementation note from Cayle: In the mobile app, if you have a validation function, the existence of any deprecated emoji should trigger a warning, and suggest that the sender upgrade.

(MM conversation can be found here: https://nomatter.tari.com/tari-ext/pl/wquo3nb15jyu5jitzdn5eogcbr)

**Acceptance Criteria**
- When a user reaches the Add Recipient screen, AND the version is on the version with the new emoji set, AND has an old emoji ID in their clipboard, they should immediately see a standard alert pop up reading: "Emoji ID Update Required" "Your recipient needs to upgrade to the latest version of Tari Aurora and copy their updated Emoji ID to transact with you" "OK"

**Comment by Jasonvdb** [comment]
@talmahaj  re the 1st acceptance criteria point, the logic for showing continue button relies on the fact that a valid public key can be constructed with those emojis. Because we can't know for certain that they have pasted a deprecated emoji ID, we're just guessing that if it's 33 emojis long and is not a valid public key then it must be from the old set. Can I suggest we reuse this error box we already have and display it after they have pasted an invalid set of 33 emojis? Because this is a piece of logic that will eventually not be needed, it would be cleaner to add in this one small check. (I can still show an alert if you prefer)
![IMG_D67025834753-1](https://user-images.githubusercontent.com/5300488/83758820-f4b1d880-a672-11ea-9225-c7f20f4a2732.jpeg)

**Comment by Jasonvdb** [comment]
And regarding the second point, we can't go back and add an alert to outdated apps. Unless this new emoji set is only going to be added much later? Then we can put this check in the 0.1.15

**Comment by kukabi** [comment]
We should also display a bottom dialog (similar to the ones we have currently) when the user enters the Add Recipient screen with an old emoji id in their clipboard.

**Comment by kukabi** [comment]
@talmahaj Emoji Ids are mapped at runtime by the FFI library, so a user with a new version of the app can never find an old emoji id in the app, i.e. the only way for an old emoji id to enter the app is through the clipboard.

**Comment by talmahaj** [comment]
> @talmahaj re the 1st acceptance criteria point, the logic for showing continue button relies on the fact that a valid public key can be constructed with those emojis. Because we can't know for certain that they have pasted a deprecated emoji ID, we're just guessing that if it's 33 emojis long and is not a valid public key then it must be from the old set. Can I suggest we reuse this error box we already have and display it after they have pasted an invalid set of 33 emojis? Because this is a piece of logic that will eventually not be needed, it would be cleaner to add in this one small check. (I can still show an alert if you prefer)
> ![IMG_D67025834753-1](https://user-images.githubusercontent.com/5300488/83758820-f4b1d880-a672-11ea-9225-c7f20f4a2732.jpeg)

@Jasonvdb works for me!

@kukabi thanks for clarifying the runtime thing, makes much more sense to me now. If it's easier to do it Jason's way than with the bottom dialog for the scenario you mentioned that's totally fine, it's OK if they only see the error message once they paste the old emoji id.

Re: not being able to add an alert to outdated apps, that was a brain fart on my part -- oops. Like the error message vs. alert, I don't think this is too big of a deal given this is a temporary thing/issue, so don't worry about it.

**Comment by Anziskavds** [comment]
Tested on iOS on version 0.2.0 on an iPhone 7. I received the below error message after the emoji ID was pasted. Is this the correct error message or should it still be the same error message as per the designs? @Jasonvdb @kukabi @talmahaj 

![IMG_B7F2DD79B07F-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/19592eb1-759c-4b96-bf8d-9429dcb1366c)

**Comment by Jasonvdb** [comment]
@Anziskavds no that's not correct. Thanks I'll investigate

**Comment by Jasonvdb** [comment]
@Anziskavds I've uploaded a new version to testflight with a fix: `V 0.2.0 (Build 98)`

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.2.0 (Build 98) on an iPhone 7.

![IMG_7D64B8DE6BFB-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/54137493-fd44-458b-abfc-dfdfe5a630f6)
