### ISSUE TITLE
Transactions show as outgoing briefly before switching back to incoming when moving app to foreground

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#418]

**Comment by Anziskavds** [comment]
Tested successfully on iOS on an iPhone 7 version 0.2.0. I tested as per the below message from Jay on Mattermost.

"Previously if you were on the app home view, switched to another app, and then reopened Tari app it would show all transactions as outgoing for like half a second before fixing itself

If you background the app and reopen and everything seems normal then it's fine"
![IMG_3197BE0DE544-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4ff5f8ea-a762-4292-a6b0-feb6a013f8e3)
