### ISSUE TITLE
eMoji ID logic issue: iOS does not accept numbers and certain characters

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#421]
**Description:**
We have found whilst testing, when numbers or certain characters are added to the emoji ID, the user does not receive the paste emoji ID banner.
After discussion it was determined that there is a logic issue within the code

**Comment by Anziskavds** [comment]
Tested successfully on iOS on an iPhone 7 version 0.2.0. I tested with a few characters, numbers, and symbols. I also tested the ones I remember of failing and it tested successfully.
