### ISSUE TITLE
QA: Transaction List screen: UI Design fixes

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#422]
Tested on iOS version 0.1.15 on an iPhone 7:

**What was tested**

- **When expanded, X icon is closer to edge than in design** - Tested unsuccessfully. The "X" looks different from the design. The "X" is placed higher on the screen.
- **Note font color is incorrect** - Tested unsuccessfully. The color looks darker than what it is on the design.
- **Whitespace between sections, transactions is incorrect** - Tested unsuccessfully. Whitespace between the transactions looks bigger than what it is on the design.
- **When expanded, nav heading font size is incorrect** - Tested unsuccessfully. The font looks a little bit bigger than what it does on the design.
- The smaller numbers in your total balance of Tari should be on the top next to the bigger numbers and not on the bottom.

**Designs and animation referenced:**
Watch from 4:22 onwards of Karim's QA video (turn on audio, he speaks through it all) now: https://www.dropbox.com/s/x634sgaij2f3nvu/Feedback-Wallet-Creation.mp4?dl=0

01:38 and 2:53 onwards of reference design video:
https://www.dropbox.com/s/8ipek9ww93urboz/Testnet%20Wallet%20FTUE.mp4?dl=0

Zeplin screen specs:
zpl.io/aNn9wmv
zpl.io/aNnAgMd

**Screenshots:**
![TDS1](https://user-images.githubusercontent.com/50987039/84141547-a24a3080-aa53-11ea-88a9-65208478657c.jpeg)
![TDS2](https://user-images.githubusercontent.com/50987039/84141555-a5452100-aa53-11ea-8a05-7eee17dd8954.jpeg)
![TDS3](https://user-images.githubusercontent.com/50987039/84141563-a8401180-aa53-11ea-899b-d6b306f0e146.jpeg)

**Comment by Anziskavds** [comment]
Tested on iOS on an iPhone 7 on version 0.2.0.

- **When expanded, X icon is closer to edge than in design** - Tested successfully. 
- **Note font color is incorrect** - Tested successfully. 
- **Whitespace between sections, transactions is incorrect** - Tested successfully. 
- **When expanded, nav heading font size is incorrect** - Tested successfully. 
- **The smaller numbers in your total balance of Tari should be on the top next to the bigger numbers and not on the bottom** - Tested successfully.


![IMG_A37E955E3E5A-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d35c7a87-9c74-4b90-a12b-f94ae2dbb8ad)

![IMG_0F2F0B21635D-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b55c0a7a-276f-465a-a276-9ef25c867f31)
