### ISSUE TITLE
[Feature] Add other cloud backup options, e.g. dropbox

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#424]
@talmahaj commented on [Tue Jun 09 2020](https://github.com/tari-project/wallet-android/issues/428)

See [parent](https://github.com/tari-project/tari/issues/1972)

**Comment by Tas4tari** [comment]
@talmahaj Moving this to Backlog as well

**Comment by TruszczynskiA** [comment]
Duplicate of https://github.com/tari-project/wallet-ios/issues/785
