### ISSUE TITLE
When the app is relaunched, all transactions temporarily display as negative values

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#426]
**Describe the bug**
when you relaunch the app the transactions temporarily display as all negative values

**Expected behavior**
When app is relaunched, values for inbound and outbound transactions should display correctly

**Video**
https://www.dropbox.com/s/v558ktl8esrg1t7/Video%20Jun%2011%2C%2010%2022%2053%20AM.mp4?dl=0

**Logs:**
[2020-06-11_10-53-16-bug-report.zip](https://github.com/tari-project/wallet-ios/files/4765953/2020-06-11_10-53-16-bug-report.zip)

**Smartphone:**
Network: rincewind
Phone: iPhone X
iOS: 13.4.1
App version: 0.1.14
App build: 93
App environment: production
Reachability: WiFi ✅
Base node: Pending first sync ⌛
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

 
**Reporter**
Robin Rath

**Comment by Anziskavds** [comment]
Tested successfully on iOS on an iPhone 7 on version 0.2.0. I received the below screen as soon as I opened the Tari app again.

![IMG_81A96AF95E64-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/21ed8486-8de1-45c3-a087-f38b42d4706a)
