### ISSUE TITLE
Back up and Restore: Redirect user to Splash screen when they select "Restore an Existing wallet" and there is no back up available

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#443]
**Use case:**
User downloads a Tari Wallet and selects the "Restore an Existing Wallet" on the splash screen and they have no back ups.

**What should happen:**

1. Select the option ""Restore an Existing Wallet"" that is displayed on the Splash screen
2. User is redirected to the ""Restore Your Wallet"" screen
3. Select the option ""Restore with iCloud"
4. User undergoes the iCloud authentication
5. User is redirected to ""Restoring your wallet"" progress screen
6. User receives the following error: **Error occurred during restoration
7. Wallet could not be restored. Backup does not exist**
8. When user selects the Close option on the error message they should be redirected back to the splash screen

**Steps to test:**

1. Uninstall the current Tari app that had a back up done
2. Navigate to iCloud and delete all back up's that were made
3. Navigate back to App store and download the Beta version of the app
4. Select the option ""Restore an Existing Wallet"" that is displayed on the Splash screen
5. User is redirected to the ""Restore Your Wallet"" screen
6. Select the option ""Restore with iCloud""
7. User undergoes the iCloud authentication
8. User is redirected to ""Restoring your wallet"" progress screen
9. Error is received by the user
10. User selects "Close" on the error message
11. User should be redirected back to the splash screen

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS on version 0.2.0 on an iPhone 7. I tested by following the steps above and I tried to restore and I received the error I wasn't redirected to the splash screen I was redirected back to the restoring your wallet screen. I'm referring to numbers 10 and 11 in the above testing steps. @SerhiiShovkoplias @Tas4tari 

![IMG_0413.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4db6d09d-3a9c-41c5-aba1-9f00bc16728b)

![IMG_0414.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/70a0c9fa-f05f-4e44-9724-74ee28ad3975)

![IMG_0415.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/032d6322-bfa0-41a0-8c35-166e7bfa2eb9)

![IMG_0417.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a20ffdcb-4134-4258-b25e-9e743d965c41)

![IMG_0418.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/0e977ceb-a0ea-43f9-bcf0-e03781726b4e)

![IMG_0419.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/3d001b24-004e-4f6d-8b90-9049f9767659)

![IMG_0420.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/1d8db117-0514-41a8-818c-10999da091b3)

![IMG_0421.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/699690a8-3927-4dea-af7a-daf24fde03cf)

![IMG_0422.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c2be0aa6-a910-406f-b74a-4890a8eec4a2)

![IMG_0423.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/aaeaaa07-aa0a-440f-a646-fd7f9d439c88)

![IMG_0426.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f332165f-7ff4-4503-a3d4-ec9a9b88c42b)

![IMG_0427.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e718316b-3778-4368-bef6-4aeb84cb7bc5)

![IMG_0428.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8b490713-8d8b-44ab-8687-053c3ea5d270)

![IMG_0429.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/278aa6a2-5f4a-4aff-b4d5-6cb376fc5d4a)

![IMG_0430.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/30557d92-3876-4001-8acc-bac89e516f84)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.3.0 on an iPhone 7.

![IMG_544BC8EA568D-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/baaf78f7-43f0-424e-9d0b-035d521669e5)

![IMG_0590.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8ecd33e2-f5c9-4a25-80b8-4930d4c136ca)
