### ISSUE TITLE
Add "Report a Bug" to Settings

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#446]
see [parent](https://github.com/tari-project/wallet-android/issues/452)

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.3.0 on an iPhone 7.

![IMG_5C373F9BD21D-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/0bd5aa57-deeb-467d-bba4-ce855400a337)
