### ISSUE TITLE
Receiving a wallet error when trying to migrating to a new phone.

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-ios#450]
If you press on the black screen/screenshot above you will see the error I’m getting to my new iPhone. I migrated from another iPhone. I can’t get access to my wallet. I could maybe delete the app and redownload it. This I suppose will create a new wallet where I can transfer my balance from the old one (the previous device is not yet wiped as I’m making sure everything migrated correctly) but I will lose transaction history.

https://www.reddit.com/r/tari/comments/hf7rpt/aurora_wallet_migrating_to_a_new_phone/

![Wallet error](https://user-images.githubusercontent.com/50451670/85668416-00674c80-b6bf-11ea-9729-ac7e426e5b9c.jpg)

**Comment by Tas4tari** [comment]
Duplicate
