### ISSUE TITLE
Set custom base node in settings

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#458]

**Comment by Anziskavds** [comment]
Steps received from Jay on how to test this: "So it's more of a power user thing, very few people even know about this. But if you copy this in your iphone clipboard: 
b81b4071f72418cc410166d9baf0c6ef7a8c309e64671fafbbed88f7e1ee7709::/onion3/lwwcv4nq7epgem5vdcawom4mquqsw2odbwfcjzv3j6sksx4gr24e52ad:18141
And then go to the app settings, it'll ask if you want to use this base node of yours as the base node of the app"

**Comment by Anziskavds** [comment]
Tested accordingly the steps provided by @Jasonvdb  and it tested unsuccessfully on iOS version 0.3.0 on an iPhone 7. After b81b4071f72418cc410166d9baf0c6ef7a8c309e64671fafbbed88f7e1ee7709::/onion3/lwwcv4nq7epgem5vdcawom4mquqsw2odbwfcjzv3j6sksx4gr24e52ad:18141 was copied to the clipboard and I went to settings on the app nothing happened.

**Comment by Anziskavds** [comment]
Retested and it tested successfully on iOS version 0.3.0 on an iPhone 7.

![IMG_0528.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5feac7e7-eeac-4e3c-acb4-445d7746e0ac)
