### ISSUE TITLE
Restore Backups: When a wallet has been restored, automatic backups should be enabled and settings retained as previous wallet

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#491]
**Description:**

- If the user had automatic backups enabled and they restore their wallet, automatic backups should be automatically enabled and all settings retained including encryption.

**Acceptance Criteria:**

- If the user restores a wallet and backups were enabled, then the backups should automatically be enabled.
- If the user had encrypted their previous wallet and they restored a wallet, the encrypted password should be retained on the restored wallet

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.3.0(115) on an iPhone 7.

![IMG_0711.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a15f6b58-0d24-4919-b457-4de8b1f37518)

![IMG_0712.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9e8cc949-1456-4ad8-aec9-a820f4ed5981)

![IMG_0713.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c90c0e40-b212-4da3-91a6-d403db1342e5)

![IMG_0714.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/26839353-cce3-4022-b669-d67c68a6060c)

![IMG_0715.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/66ae0bab-ced1-4ce3-994c-2e0ffee4e661)

![IMG_0716.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f98b0b63-dbd4-4dff-aefd-3275af5f4a16)

![IMG_0717.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9d523122-5800-4759-8801-904c682bac83)

![IMG_0718.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/1428e50a-abce-4ed6-bb66-8b7e9ba26bad)

![IMG_0720.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ed04c7d1-d68a-4bbe-b5f8-1feb1ff9113c)

![IMG_0721.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/30e85ac4-98f4-42f4-8b41-2a3a0879d608)

![IMG_0722.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/01d5f757-208a-44d1-8917-fc3d5d893dc2)

![IMG_0723.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/26e36401-dbac-46f0-8839-ec1559e60ed9)

![IMG_0724.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/849a9956-47e1-4da5-a0aa-9ca314e2d56a)
