### ISSUE TITLE
Backups: Wallet Backups screen: Scheduled section differs from Android 

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#492]
**Description**
Currently on iOS, the "Add password/change password" section is hidden for users and the Scheduled state icon is an empty progress bar

**Acceptance Criteria:**

- Change Scheduled state icon to match the design: Currently on Android the Scheduled state icon displays as a green tick, this will need to be changed as per the new design: http://zpl.io/2j6op8A
-  Display the "Secure your iCloud backup/Change your secure password" section with the Wallet backups screen as it is on Android
- Screens attached for reference

**Android**
![up_to_date_android (1)](https://user-images.githubusercontent.com/50987039/87960927-4b556380-cab5-11ea-9053-1b0d9b3788b1.png)

**iOS**
![up_to_date_ios (1)](https://user-images.githubusercontent.com/50987039/87960945-514b4480-cab5-11ea-84e0-92b2632d39df.png)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.3.0(115) on an iPhone 7.

![IMG_0697.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/91891f3a-55c4-4d40-999e-55cfd4fb7c28)

![IMG_0698.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/cbc5d456-26a7-4292-9220-ea60907f6f98)
