### ISSUE TITLE
Shiny new bottom tab navigation

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#494]
See in-context specs posted as comments at zpl.io/2vJq1We

Note that nav should only appear on tx list screen

**Comment by Anziskavds** [comment]
Testing successfully on iOS on version: 0.4.0 on an iPhone 7:
**Requirements from design:**

- Nav should only appear on tx list screen: **Tested as per the updated discussion on Mattermost:** "Mattermost discussion:
Beyond that, we could have the nav display on JUST the primary navigation screens, but not their children (e.g. main settings screen, but not subsetting screen -- transactions list, but not transaction details). This is a pretty common pattern, for example, go to your FB app, select the Profile nav item, and try to edit something in your profile -- the child screens under the primary ones do not display the nav:" **Tested successfully. Nav displays on all primary screens and does not display in sub-setting screen or Transaction details screen."**
- Nav to tx list screen: **Tested successfully. When the user selects the Home icon they are redirected to the Transaction List screen.**
- Cart icon opens store modal: **Tested successfully, when the user selects the Cart icon, the TTL store modal is opened.**
- Multidirectional icon opens send Tari flow: **Tested successfully. When the user selects the icon they are taken to the Send Tari flow.**
- Profile icon: nav to profile screen: **Tested successfully. When the user selects the profile icon they are taken to their profile and the settings icon is no longer displayed in the user's profile screen.**
- Settings icon: Remove settings icon from profile screen -- it should only appear in nav now: **Tested successfully when the user selects the Settings icon they are now taken to the app Setting page.**

Screenshots:

![IMG_0789 2.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/27124f3a-19a5-4ec0-8815-ac65658398af)

![IMG_0790.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b9a47a71-6bd1-4321-aa0b-5837c0ef0993)

![IMG_0791.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/69b3f4d5-d209-4e0b-8d72-c8f4541183e7)

![IMG_0792.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c1f68b29-2982-4f30-bc44-8f16a9abaed8)

![IMG_0793.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f0bf5801-78e2-4c10-9ef1-947e9691fa7e)

![IMG_0794.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e37b7cd7-02dd-4e0c-af66-4e479227409c)

![IMG_0795.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8d4556ec-1264-4503-873a-87e506c112c0)

![IMG_0796.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b4a56a67-6584-43bd-8660-c127231a0acc)
