### ISSUE TITLE
Tx list screen design tweaks

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#495]
See in context specs at https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5f167670e4bc278d51faf26d

(Note there is also one font color change on the tx detail screen)

**Comment by Jasonvdb** [comment]
![Screenshot 2020-07-22 at 16 33 09](https://user-images.githubusercontent.com/5300488/88189213-1b36cd80-cc39-11ea-8acf-b43dd64f6a75.png)

@talmahaj if it's less than 1 hour ago then what should it display? 
Going with `2min ago` for now instead of `0h ago`

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.0 on an iPhone 7.

Test report: https://big-neon.ontestpad.com/script/258/report

![IMG_0789.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/62ecc58b-087e-4dab-9933-a161b8804bc7)

![IMG_0788.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2a8914cc-30e2-4b92-a038-4da3df70ff42)

![IMG_0787.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/55a938fa-ec23-4044-b61d-46ea0ed64b3b)

![IMG_0786.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/904a9b88-9c72-4a1b-af54-e4902b4904da)

![IMG_0785.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d8fb1479-8876-4d8a-93f6-d19085621427)

![IMG_0784.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7bfa921c-0346-47a7-a09e-95233b016cdd)

![IMG_0783.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ce7ec3d2-826f-4ac5-879d-eaf8324a76b3)

![IMG_0782.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/25c8d5f2-da05-4ca0-b5bf-70a7b9543adc)
