### ISSUE TITLE
Back up prompt modal - Incorrect modal shows for the fourth transaction or more accepted and with a balance of 8000+ tXTR

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-ios#497]
The incorrect modal was received when I accepted the fourth transaction and my balance was 8000+ tXTR. I received the same modal for the 3 transactions(https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7caa4e8916298490df31)

**Expected behavior**
- When user reaches 8,000+ tXTR, AND it’s their fourth accepted transaction or later (otherwise they’ll see the first modal above) display the following modal: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca94e8916298490ded9

This was the modal I received:

![IMG_0600](https://user-images.githubusercontent.com/50451670/88176504-aa3aea00-cc27-11ea-85fa-50767d4b8e90.PNG)

**Comment by Jasonvdb** [comment]
@Anziskavds pushing a change for this just now. 

We have 3 backup prompt triggers. Previously if you jumped straight to meeting the requirements for prompt 2, then you would also meet the requirements for prompt 1 and the app would first show you prompt 1 first. With this change if you meet the requirements for prompt 1 and 2 then you will only be shown prompt 2.

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS on version 0.3.0(115) on an iPhone 7. No prompt modals were received, not one for the 3rd accepted transaction and also no prompt modal received for 8000+ tXTR and the 4th or more transaction accepted.

![IMG_22B243A35C03-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7f6d0256-c769-47b1-a602-be2a95865524)

**Comment by Jasonvdb** [comment]
@Anziskavds did you delete the app and reinstall before trying? The prompts only show up once for the user

**Comment by Anziskavds** [comment]
@Jasonvdb Yes, it was a newly installed wallet.

**Comment by Jasonvdb** [comment]
@Anziskavds can you retry? I'm able to get this on the latest testflight 

![IMG_3497](https://user-images.githubusercontent.com/5300488/88555156-b6f47f00-d027-11ea-93c4-b665111b14eb.PNG)

**Comment by Anziskavds** [comment]
Tested on iOS on version 0.3.0(121) on an iPhone 7. I only receive the below prompt. I do not receive the second prompt as per the designs. https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca94e8916298490ded9

cc @Jasonvdb @Tas4tari 

![IMG_0730.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e360cf46-93a9-4b3b-8f39-c5247317a2f0)

**Comment by Jasonvdb** [comment]
@Anziskavds @Tas4tari I just went through this test myself and it is working. Just want to clarify we're all checking the exact same criteria for these prompts. 

Requires 3 or more incoming transactions:
![IMG_3505](https://user-images.githubusercontent.com/5300488/88774145-5e39f900-d183-11ea-89f6-5a8cbaf0a63d.PNG)

Requires 4 ore more incoming transactions and a balance greater than or equal to 8000:
![IMG_3506](https://user-images.githubusercontent.com/5300488/88774600-ef10d480-d183-11ea-927b-750a4e700e28.PNG)

Requires 5 or more incoming transactions, balance greater than or equal to 25000 and has connected iCloud backups but has not set a password:
![IMG_3507](https://user-images.githubusercontent.com/5300488/88776318-1799ce00-d186-11ea-8ed5-2aeaf7574efb.PNG)

**Comment by Anziskavds** [comment]
@Jasonvdb That's correct I also receive the above. I'm referring to the second prompt. As per the designs, it should read "It's time to backup your wallet". ![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/6cb164f4-0b55-4085-b94c-35fb770897b6)

cc @Tas4tari

**Comment by Tas4tari** [comment]
@Jasonvdb Is there any feedback for this?

**Comment by Jasonvdb** [comment]
Will fix soon as we're done with giphy

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.0(132) on an iPhone 7.

![IMG_0848.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4f2b6904-7ed8-4969-a68a-1cd5d17ef933)
