### ISSUE TITLE
Back up prompt modal - Redirecting to the incorrect settings screen

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-ios#498]
When a user clicks on the "Back up wallet" button they get redirected to the first settings screen and not the settings screen as per the requirements.

**Expected behavior**
- Hitting Back Up Wallet should send the user to the backup section within Settings: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5ecc7ca8487aa129234090be

I was redirected to this screen:

![IMG_0604](https://user-images.githubusercontent.com/50451670/88176820-26cdc880-cc28-11ea-8b6c-7b47ff63ee87.PNG)

**Comment by Tas4tari** [comment]
This implementation will be left as it
