### ISSUE TITLE
Automated backups - "Out of date" status doesn't show

### ISSUE THREAD

**Issue by Anziskavds** [tari-project/wallet-ios#499]
When a user's backups are out of date, the status "Out of date" in red doesn't show. It's only the indicator that shows (The exclamation mark in red). Also, the "Last successful backup" date doesn't show when the backups are out of date.

![IMG_0580](https://user-images.githubusercontent.com/50451670/88182698-cee78f80-cc30-11ea-9a92-af1d506cd534.PNG)

![IMG_0612](https://user-images.githubusercontent.com/50451670/88182363-5f71a000-cc30-11ea-87c7-6c3df7117e28.PNG)

**Comment by Tas4tari** [comment]
User was still unable to retrieve the error.
@Jasonvdb @SerhiiShovkoplias Do you have any ideas on how to reproduce this?
cc @Anziskavds

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.3.0(115) on an iPhone 7. I disabled backups on the device for the Tari App and went back and opened the app and checked the status because it was disabled the backups weren't up to date.

cc @Tas4tari @Jasonvdb @SerhiiShovkoplias 

![IMG_0702.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b81cfdf6-303a-489f-a75c-5afe783f21c7)
