### ISSUE TITLE
Giphy Integration - Core Functionality

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#501]
@talmahaj commented on [Wed Jul 22 2020](https://github.com/tari-project/wallet-android/issues/502)

We hypothesize that if we make transacting more fun, more people will want to tell others about Tari. Adding a fun factor to transactions also helps differentiate the Tari brand from that of other crypto projects, most of whom have apps that are quite dry and dull to use.

And since we already have emojis, the next most obvious "fun" thing to add is gifs. Several popular P2P payment apps outside the crypto space encourage fun metadata like images, emojis, gifs, and are not necessarily deemed any less trustworthy than their more bank-like competitors.

(After we launch the initial functionality, we'll explore enhancements like being able to intelligently generate gif suggestions based on the note text -- will mention in a separate ticket).

---

### Docs
https://developers.giphy.com/

### Specs

**Add a Note screen**
- Adding a note OR a gif should now be mandatory, but user does not need to add both in order for submit transaction button to become enabled.
- Each time screen is loaded, gif carousel should display random gifs from the "money" search query -  https://giphy.com/search/money
- User can only add one gif. Whenever a gif is selected, the gif carousel should slide down out of sight (and slide back up automatically if user removes the selected gif)
- Slide to Send button is now full-width and fixed to top of keyboard
- Tapping Search Giphy (either the fixed black button, or the last item in the carousel) brings up full-screen search. ITapping outside of the search modal or grabbing drawer should close modal and does not need to preserve search query in case user opens it up again - they can see the default again
- JUL 30 EDIT: Cropping gifs to match design rather than using default module is now out of scope for this ticket
- JUL 30 EDIT: slide to send should sit at the bottom of the screen if keyboard is collapsed
- AUG 5 EDIT: we can have the "Powered by giphy" on the add note screen and remove it everywhere else, we don't need to show it on the transaction list or detail page

**Transaction List screen** 
- If a transaction doesn't have a note attached, only a gif, just collapse the row where the note would've appeared so there isn't extra empty whitespace
- gif should always show in full height (but fixed width per design mockups) in feed

**Transaction Detail screen** (not included in design files)
- We do not have a mockup of this in Zeplin, but gif should show be at full height and fixed width such that it is flush on the left and right with the other content on the screen (that is, the same width as the white status bar, the grey divider, etc.)
- JUL 30 EDIT: Remove transaction ID from bottom of screen
- JUL 30 EDIT: Make screen scrollable to account for extra vertical space needed when there is a gif

**Case Handling**
- JUL 31 EDIT: If gif fails to load on tx list OR tx detail screen, show the gif failed state with a retry button (@karim-tari to provide design). When user taps retry button, gif returns to loading state until success or failure.
- JUL 31 EDIT: While gif is loading, display loading state (@karim-tari to provide design)

**Comment by Tas4tari** [comment]
@Jasonvdb Please see @talmahaj responses to your questions below:

- "Where does the slide to send sit when the keyboard is dismissed?"

slide to send would sit at the bottom of the screen, right @karim ?

- "Should we be hiding the giphy carousel when keyboard is dismissed? I considered finding a way to not allow them to drop the keyboard but we might have an issue on small phones."

I think we can just keep the carousel, seems like an edge case honestly (i agree with you about disabling it if it were easily possible but nbd)

- "Can’t seem to find a way to limit the default “money” gifs and add the grey “Search giphy” block at the end of the carousel. It has infinity scrolling. The top left black button works fine."

It's cool, shouldn't be a big deal!

**Comment by talmahaj** [comment]
@Tas4tari pls be sure to also add these answers to the android ticket and change the specs with the date, e.g. UPDATE JUL 31 in the original description as needed in case someone misses it in the comments. Thanks!

**Comment by talmahaj** [comment]
The following edits have been made to the original description:

**Add a Note screen**
- JUL 30 EDIT: Cropping gifs to match design rather than using default module is now out of scope for this ticket
- JUL 30 EDIT: slide to send should sit at the bottom of the screen if keyboard is collapsed

**Transaction Detail screen**
- JUL 30 EDIT: Remove transaction ID from bottom of screen
- JUL 30 EDIT: Make screen scrollable to account for extra vertical space needed when there is a gif

**Comment by talmahaj** [comment]
**Case Handling**
- JUL 31 EDIT: If gif fails to load on tx list OR tx detail screen, show the gif failed state with a retry button (@karim-tari to provide design). When user taps retry button, gif returns to loading state until success or failure.
- JUL 31 EDIT: While gif is loading, display loading state (@karim-tari to provide design)

**Comment by Tas4tari** [comment]
@Anziskavds Test cases for GIPHY integration has been scripted as per requirements on ticket:
[GIPHY Integration.pdf](https://github.com/tari-project/wallet-ios/files/5017768/GIPHY.Integration.pdf)

**Comment by Tas4tari** [comment]
**Note screen:**

- Aug 5 EDIT: we can have the "Powered by giphy" on the add note screen and remove it everywhere else, we don't need to show it on the transaction list or detail page. Added to the description as well

**Comment by Anziskavds** [comment]
Tested on iOS on version 0.4.0(132) on an iPhone 7. I only found that the "Search Giphy" screen is different from the design on Zeplin but seems to fine for now as per the discussion on Mattermost but I just want to confirm with @talmahaj before closing the card. ![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/0f427461-e564-4194-b345-58757bbd5cad)

Current design:
![IMG_0836.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/3219d63f-8d54-4a96-8a14-a34278b404bb)

Test Report: https://big-neon.ontestpad.com/script/257/report

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.0(132). Confirmed with Tal in tonight's stand up meeting and she confirmed that "Search Giphy" is also fine.

**Comment by Anziskavds** [comment]
Tested successfully on iOs on version 0.4.0 (132) on an iPhone 7. Tal confirmed in stand up 14 Aug 2020 that the design is currently correct.
