### ISSUE TITLE
Cannot do first backup - stuck at "in progress".

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#506]
**Describe the bug**
When I first toggle on the backup switch after a clean install, the installation status is stuck at "In Progress".
When I go back to home screen, I see white empty space in place of the pull-to-refresh component.

**To Reproduce**
0. iCloud & iCloud Drive are enabled.
1. Make a clean Aurora install.
2. Go to backup settings and turn backup on.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13.5

**Screenshots**
![Screen Shot 2020-07-24 at 15 40 17](https://user-images.githubusercontent.com/2969501/88392046-05a1df00-cdc4-11ea-99e4-3437309c96ff.png)
![Screen Shot 2020-07-24 at 15 40 27](https://user-images.githubusercontent.com/2969501/88392074-0fc3dd80-cdc4-11ea-83bd-26bd7021bf72.png)

**Comment by kukabi** [comment]
Note: if I restart the app then a backup is made and status switches to "up to date".

**Comment by kukabi** [comment]
I've found the reason for this:
![IMG_E8531](https://user-images.githubusercontent.com/2969501/88660942-570ddf00-d0e0-11ea-8a6b-ff8125b759d3.JPG)

@SerhiiShovkoplias we have to find a way to provide feedback to the user about this case. Is there a way to detect it?

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.3.0(123) on an iPhone 7.

![IMG_0759.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5654b94f-1541-43f6-a6f6-274ed407658c)

![IMG_0760.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/cd642147-68f2-43f6-a805-d1043a272263)

![IMG_0761.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/aa877ea8-6fb2-4105-b8f6-34046c0b9b99)

![IMG_0762.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b661b15a-d930-4d83-98dd-a68a024ff11d)

![IMG_0763.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f7af2284-ecce-42cf-8550-0640132d0794)

![IMG_0764.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f86bf59d-297e-4da5-9989-3e73b3b44a26)

![IMG_0765.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b944547a-fc3b-46fe-908f-1f6fa326b833)
