### ISSUE TITLE
Pull-to-refresh component shows "Backup successful" when backup is turned off.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#507]
**Describe the bug**
Pull-to-refresh component shows "Backup successful!" at startup when backup is disabled.

**To Reproduce**
Start the app with backup disabled and observe the pull-ro-refresh component.

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13.5

**Screenshots**
![Screen Shot 2020-07-24 at 15 42 24](https://user-images.githubusercontent.com/2969501/88392344-7e08a000-cdc4-11ea-87b8-f6e300ac0f4c.png)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.3.0(123) on an iPhone 7.

![IMG_0741.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4f874ed2-5302-4207-82d6-4d2aa204851d)

![IMG_0742.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/011b53d2-7bcb-452f-8161-2a62e8b31f8f)

![IMG_0743.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/93b89c26-d983-4e93-a962-f5d13ec4a2da)
