### ISSUE TITLE
Status bar shows black for maximized list after first install

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#509]
**To Reproduce**
1. Clean-install the app.
2. Reach home screen.
3. Maximize the list.

**Screenshots**
![IMG_8505](https://user-images.githubusercontent.com/2969501/88394896-e194cc80-cdc8-11ea-96c4-eeec613aa233.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13.6

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.3.0(123) on an iPhone 7.

![IMG_0744.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/90dac819-1521-4460-a947-f3eaaa2491f5)
