### ISSUE TITLE
Restart after failed backup: backup stuck at "In Progress"

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#510]
**Describe the bug**
With backup status stuck at "In Progress" I terminate the app, and when I restart I first see a backup error display, then the app opens and it's still stuck at "Backing up your wallet..." state. After the pull-to-refresh component disappears, the tx list does not return back to its original position.

**Screenshots**
![IMG_E8507](https://user-images.githubusercontent.com/2969501/88395555-ef971d00-cdc9-11ea-9771-f59e053e529e.JPG)
![IMG_E8508](https://user-images.githubusercontent.com/2969501/88395558-f1f97700-cdc9-11ea-9aa9-5c83a15f5b77.JPG)
![IMG_E8509](https://user-images.githubusercontent.com/2969501/88395564-f3c33a80-cdc9-11ea-91d7-d280fc4c99a6.JPG)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13.6

**Comment by kukabi** [comment]
The reason for this case is [here](https://github.com/tari-project/wallet-ios/issues/506#issuecomment-664991152), solution will apply for this case too hopefully. @SerhiiShovkoplias

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.3.0(123) on an iPhone 7.

![IMG_0751.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2b242419-4a76-446f-bee5-c8614b4fce5c)

![IMG_0752.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/56e0f885-8e84-49bc-a013-cd646ccdcb86)

![IMG_0753.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e8e90758-e8b1-4938-8134-d79a1ae8b9a6)

[Uploading... IMG_0754.PNG ]

![IMG_0755.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/6a99ccad-8bb0-4d3b-b5e5-f7ab3e254e37)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.3.0(123) on an iPhone 7.

![IMG_0751.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2b242419-4a76-446f-bee5-c8614b4fce5c)

![IMG_0752.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/56e0f885-8e84-49bc-a013-cd646ccdcb86)

![IMG_0753.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e8e90758-e8b1-4938-8134-d79a1ae8b9a6)

![IMG_0754.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/3ef10a2d-037e-46d4-9ee2-7c2983d617b8)

![IMG_0755.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/6a99ccad-8bb0-4d3b-b5e5-f7ab3e254e37)
