### ISSUE TITLE
Wrong copy and state after failed scheduled backup

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#512]
**Describe the bug**
If I turn off my internet connection after a backup is scheduled, the backup fails at the scheduled time with the following modal with probably wrong copy:
![IMG_E8514](https://user-images.githubusercontent.com/2969501/88402830-56213880-cdd4-11ea-9806-4b95ef3ccadf.JPG)

At this state I think the backup is practically out of date, yet the backup settings and settings screens show up to date state:
![IMG_E8515](https://user-images.githubusercontent.com/2969501/88402993-8d8fe500-cdd4-11ea-9290-1e21f2ac2d5a.JPG)

![IMG_E8516](https://user-images.githubusercontent.com/2969501/88403094-badc9300-cdd4-11ea-843b-2183a80e88d0.JPG)

**Expected behavior**
I think backup settings and settings screens should show out of date state.

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.3.0(123) on an iPhone 7.

![IMG_0766.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9881fc95-fb61-4290-a44f-d6b1a5fad626)

![IMG_0767.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/58233037-efff-4bec-ba24-7ecadaa068b2)

![IMG_0768.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2f78fd7f-26f1-45c2-af9e-7ea6414aecc2)

![IMG_0769.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/5b1aee2a-3615-48f7-9454-9647a4252ab2)
