### ISSUE TITLE
"Authentication failed" options have no effect in settings screen.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#513]
**Describe the bug**
`Try again` and `Open settings` options in `Authentication failed` modal have no effect after a failed auth in settings screen.

**To Reproduce**
1. Go to settings screen.
2. Click `Backup Up Wallet`
3. Click `Cancel` in the touch id modal.
4. Click either `Try again` or `Open settings` in the `Authentication failed` dialog that follows.

**Expected behavior**
I think the dialog could have a single `Ok` action.

**Screenshots**
![IMG_E8513](https://user-images.githubusercontent.com/2969501/88403751-992fdb80-cdd5-11ea-89b5-e1aeb7eea657.JPG)

**Comment by Anziskavds** [comment]
@kukabi I'm not receiving the screen you attached on this card. After I clicked on "Wallet Backups", I receive the Touch ID and I use the incorrect finger for it to fail and then I receive a pop up to or either enter a passcode or to click cancel. Please advise?

![IMG_0735.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7843bfab-d24b-4ad2-84f2-07f322485490)

![IMG_0736.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/de438be1-99f7-4c15-b957-f1b6f0b68d77)

**Comment by kukabi** [comment]
@Anziskavds this is the expected behaviour. You may close the ticket if you don't see the dialog I shared the screenshot of when you "Cancel" touch id.

**Comment by Anziskavds** [comment]
@kukabi Thanks Kutsal. Tested successfully on iOS on version 0.3.0 on version 0.3.0 on an iPhone 7.

![IMG_0735.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7843bfab-d24b-4ad2-84f2-07f322485490)

![IMG_0736.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/de438be1-99f7-4c15-b957-f1b6f0b68d77)
