### ISSUE TITLE
Automated backups: Disable backups: When user disables a back up, alert the user that their backup will be deleted

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#515]
**Description:**
Disabling a backup deletes all previous backups that were made and therefor when a user selects to "Restore an Existing Wallet" they receive an error message however the user should now receive a alert

**Acceptance Criteria:**
- When user tries to disable the backup, user should receive an alert informing them that all previous backups will be deleted if they choose to disable the back up
- Alert should be similar to what was done on Android, except in the title the word "backups" should now state "backup", see video below:
https://drive.google.com/file/d/1z4bafMHN3NxmW0OuuFKTa474RRVLBbCO/view?usp=sharing

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.3.0(123) on an iPhone 7.

![IMG_360E851C0203-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/325017be-448d-48cd-9e83-b13df4c6165a)
