### ISSUE TITLE
Update tx list timestamp in real time

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#524]
@talmahaj commented on [Thu Jul 30 2020](https://github.com/tari-project/wallet-android/issues/517)

Per the tx redesign tweaks ticket #488 there is now a "[#min]m ago" timestamp for txs initiated in the past hour. However, the number of minutes does not dynamically update in real time.

**Acceptance Criteria**
- the number of minutes displayed in the UI should dynamically increment by 1 minute every minute to always show the accurate # of minutes since the tx was initiated -- even if user keeps the tx list screen in the foreground

**Comment by Anziskavds** [comment]
Testing in progress.

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.1 (139) on an iPhone 7.

![IMG_0901.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/09518418-3755-49af-8c42-63da1e012611)

![IMG_0902.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e9b5ab97-bbdd-47a2-ad96-fbc5c910c54c)

![IMG_0903.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/33353afa-48ad-44f8-b3c2-23bd0f387121)
