### ISSUE TITLE
TX detail view scrollable

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#533]

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.0 on an iPhone 7.

![IMG_E03748563338-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e3f44858-b310-44e7-859c-2cf1e2fae44d)

![IMG_E03748563338-2.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/38f9c5c8-e2e3-43d9-994a-028720f0b918)
