### ISSUE TITLE
Transaction List screen: Shadow at the bottom of the status bar is getting cut off

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#537]
**Describe the bug**
If you look closely, the bottom of the status bar shadow is getting cut off a bit

**Screenshots**
![IMG_7635](https://user-images.githubusercontent.com/50987039/89864738-c4c00d80-dbac-11ea-8ac2-df43334ac28b.PNG)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.1(137) on an iPhone 7.
![IMG_AE7FAF241164-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8654ab49-bd73-443d-bac5-bfab750c131f)
