### ISSUE TITLE
GIPHY Integration: When GIF is added to Note screen, it appears squashed

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#538]
**Describe the bug**
gif is squished instead of full height

**Screenshot:**
![IMG_7639](https://user-images.githubusercontent.com/50987039/89864882-03ee5e80-dbad-11ea-8d56-e83dc52b6ce8.PNG)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.0(131) on an iPhone 7.

![IMG_3498BA18FB30-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d6fdf78b-83c4-464e-b621-6be5c4764e80)

![IMG_3498BA18FB30-2.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/954e597f-754e-46c9-bddf-1eca80fd0164)

![IMG_3498BA18FB30-3.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e5670173-33dc-40ae-9c9e-b3fb69e94acb)

![IMG_3498BA18FB30-4.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/3f2a4eb3-bdaf-459b-a795-72b7cdda519d)
