### ISSUE TITLE
GIPHY Integration: Note screen: Powered by GIF label is in the incorrect place and Search label is not as per design

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#539]
**Describe the bug**
Can we have the powered with giphy be on the right side flush with the search button? And can we have the search button read "search gifs" and have less padding on the left and right so it looks more like the design mockup?

I don't know if this is a limitation of the giphy component, but it appears in a bit of a jarring transition -- not sure if there's a way for it to slide or fade in at all?

**Screenshots**
![IMG_7641](https://user-images.githubusercontent.com/50987039/89865079-5891d980-dbad-11ea-8800-0e847d1025a1.PNG)

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS on version 0.4.0(131) on an iPhone 7. The search button reads "Search Giphy" instead of "Search Gifs" as per the above description. 
@Jasonvdb 
![IMG_18CC73CEACB7-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7a44a845-ac06-4ff6-bf52-709568b6c766)

**Comment by Jasonvdb** [comment]
@Anziskavds that is correct https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5f163ca8a3d28d9d977df68d

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.0(132). Confirmed with Tal in tonight's stand up meeting and she confirmed that "Search Giphy" is also fine.
