### ISSUE TITLE
GIPHY Intregration: GIF search is cut off when in full screen

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#540]
**Describe the bug**
GIF search is cut off in full screen for some reason

**Screenshot:**
![IMG_7629](https://user-images.githubusercontent.com/50987039/89865462-1321dc00-dbae-11ea-97f8-523f6b3baa80.PNG)

**Comment by Tas4tari** [comment]
As per @kukabi try hiding the keyboard when opening the Search screen

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.0(132) on an iPhone 7.

![IMG_C57599BCA1FD-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/dd3df00a-e046-4012-8833-5657f9182ea2)
