### ISSUE TITLE
iOS App Improvements: Auto crash on app

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#541]
**Description:**

- it auto-crashes for me whenever i try to open it fresh

**Comment by Jasonvdb** [comment]
@Tas4tari these are 4 separate issues

**Comment by Tas4tari** [comment]
> @Tas4tari these are 4 separate issues

Yep, I'm actually breaking them out as we speak

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.0(131) on an iPhone 7. I didn't receive an auto crash on the app when I open it fresh. I also tried with uninstalling and installing again and it also hasn't crashed.

**Comment by Tas4tari** [comment]
@Anziskavds Can you also maybe try  the clean install on the iPhone X on Browser-stack, as this one of the devices that it had occurred on. Happens with a clean install of the app

**Comment by kukabi** [comment]
@Tas4tari I think we cannot have iOS releases on BrowserStack, @Jasonvdb correct me if I'm wrong.

**Comment by Jasonvdb** [comment]
@kukabi @Tas4tari browserstack works but only if you download the app through testflight
