### ISSUE TITLE
Transaction lIst screen: Make it so the list item goes under the status instead of over it when you swipe up

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#542]
**Describe the bug**
This one is lower priority but would be great if we can make it so the list item goes under the status instead of over it when you swipe up (it would also fix the cut off shadow thing as well i guess)

**Screenshot:**
![IMG_7650 2 (1)](https://user-images.githubusercontent.com/50987039/89867226-28e4d080-dbb1-11ea-803e-582c906f5e8a.PNG)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.1(137) on an iPhone 7.

Video: https://drive.google.com/drive/my-drive

![IMG_0888.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/1b5963d6-18eb-4bae-855f-12e93f1d6e05)
