### ISSUE TITLE
Cancelled transactions still displayed as Pending

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#544]
**Describe the bug**
Bradwin EightyFour, [Aug 9, 2020 at 7:25:28 PM]:
Anybody else having sent transactions cancelled after pending in the  wallet?

>> Balances:
Available balance: 171707.423744 T
Pending incoming balance: 18434.061911 T
Pending outgoing balance: 719434.069611 T

400,000.00 T in transactions were cancelled (200k x2) But are still showing in the pending. I believe one of  them is past the 12 hr window, though the wallet was open to receive in the 12 hr frame.

**User:**
@Bradwin84

**Logs:**
[2020-08-09-12-10-58-bug-report.zip](https://github.com/tari-project/wallet-ios/files/5055675/2020-08-09-12-10-58-bug-report.zip)

**Screenshots**
![photo_2020-08-11 10 14 38](https://user-images.githubusercontent.com/50987039/89874185-cba24c80-dbbb-11ea-8813-e23aaa266186.jpeg)
![photo_2020-08-11 10 14 47](https://user-images.githubusercontent.com/50987039/89874196-cf35d380-dbbb-11ea-800e-1571fd45a925.jpeg)

**What it looked like on the wallet:**
![photo_2020-08-11 10 18 33](https://user-images.githubusercontent.com/50987039/89874363-0906da00-dbbc-11ea-9b1f-e3d300144647.jpeg)

**Comment by Jasonvdb** [comment]
If I understood this right I don't think this is something we can fix on the app side. Once the sender cancelled a transaction the receiver can still get the store and forwarded message for the incoming transaction and the receiver has no idea the sender actually cancelled it. The incoming txs will just never complete. @talmahaj @Tas4tari

**Comment by Tas4tari** [comment]
> If I understood this right I don't think this is something we can fix on the app side. Once the sender cancelled a transaction the receiver can still get the store and forwarded message for the incoming transaction and the receiver has no idea the sender actually cancelled it. The incoming txs will just never complete. @talmahaj @Tas4tari

Apologies @Jasonvdb I just realized the title was misleading as well so changed it

**Comment by Jasonvdb** [comment]
So not really a bug but a current limitation of the system. When a sender cancelled a transaction the receiver has no way of knowing it has been cancelled so the transactions just get stuck there as pending. 

But Phil is putting together a proposal to improve Tx send robustness by introducing automagic resends and tolerating repeats and as part of that I will introduce a new message for cancellation. 

Can we close this as it's a feature being worked on in the protocol and not an iOS bug?

**Comment by Tas4tari** [comment]
@Jasonvdb Thank you for the analysis. Will discuss in stand up before closing

**Comment by Tas4tari** [comment]
Closing this issue as per the above comment
