### ISSUE TITLE
iOS App Improvements: When app is opened, the white gem appears blurry

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#545]
**Describe the bug**
As soon as it opens, the white gem that initially appears looks blurry? It happens so fast I can't be sure it's not the transition stuttering maybe

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.0(132) on an iPhone 7. It doesn't seem to be blurry.

Video: https://drive.google.com/drive/folders/17PPL0qtm_EBIRbSjHTVgxJHFTQRNfdqD

![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/3921fdea-c2c6-4365-9028-4d2e2addd892)
