### ISSUE TITLE
iOS App Improvements: Transaction List Status overlaps

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#546]
**Describe the bug**
Sometimes the "You are up to date" overlaps the "checking for updates" before the latter disappears

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.1(137) on an iPhone 7.

The transaction list statuses don't overlap, "checking for updates" slides up and "You are up to date" follow shortly after the "checking for updates" status by also sliding up. 

Video: https://drive.google.com/drive/my-drive

![image.png](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/243568de-9e1f-4636-b687-6e8834c9b69e)
