### ISSUE TITLE
iOS App Improvements: Pull to refresh flicker

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#547]
**Describe the bug**
Sometimes there's a big purple flicker of something under the first list item when i swipe down to refresh... i can't make out what it is

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.1(137) on an iPhone 7.

Video: https://drive.google.com/drive/folders/17PPL0qtm_EBIRbSjHTVgxJHFTQRNfdqD
