### ISSUE TITLE
Emoji button on TX detail view gets fade applied

### ISSUE THREAD

**Issue by Jasonvdb** [tari-project/wallet-ios#550]
Looking good in general, one thing:
![IMG_8578](https://user-images.githubusercontent.com/2969501/89902829-9ca5ce00-dbef-11ea-9895-18863b7a90c0.PNG)

 Is there a quick fix for this?

_Originally posted by @kukabi in https://github.com/tari-project/wallet-ios/pull/548#issuecomment-671946601_

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.0 (136) on an iPhone 7.

![IMG_B5DC4EE24BB0-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/39caab36-96ab-4139-9589-0c0af84f96f0)

![IMG_F6829680954E-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/c1e5d167-f6d1-4529-acdb-e074cde45c02)

![IMG_C3BE03D7FCFC-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/546ebac5-dc69-4258-ac87-142dd686fd45)
