### ISSUE TITLE
Cancelled transaction disappears from the list.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#558]
**To Reproduce**
1. Send some Tari to TariBot.
2. Go to transaction details screen and cancel the transaction.
3. Go back to the transaction list screen.
4. Transaction should be there but it's removed from the list.

**Expected behavior**
Cancelled transaction should be in the list.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13.6.1

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.0 (135) on an iPhone 7.

![IMG_503E16E86CC5-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f046db15-5e59-4892-9845-8fa0dbf8b5e1)

https://drive.google.com/file/d/1dHRRUzKwhZDG6Ts8hMuXClfZ7GD-WlIM/view?usp=sharing
