### ISSUE TITLE
Pull to Refresh: Remove Backup scheduled status from the Pull to refresh status component

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#567]
**Description:**

- The Pull to Refresh status component on the tRansaction List screen is also used to display the Backup scheduled status which is not ideal as the component was not built for this.
- As per @kukabi if you background and foreground the app again the Pull to Refresh statuses. gets overridden by the Backup scheduled status
- Suggestion to possibly create another field/component for the Backup scheduled status on the Transaction list screen from @kukabi 

**Consensus:**
18 August 2020: Remove Backup scheduled status from Pull to refresh status component

**Screenshot:**
![IMG_8599](https://user-images.githubusercontent.com/50987039/90536270-1f90d080-e17c-11ea-9b8f-e2507210b6e0.PNG)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.1 (139) on an iPhone 7.

![IMG_4D21F99EA5C2-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/981ae187-8055-487c-a95c-5f9f5669923e)

![IMG_897E6813F79A-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/3eb1f8d5-35d3-4ead-8d68-bb7b8bafe0ae)

![IMG_897E6813F79A-2.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/33c77edc-a6c6-4594-b3fb-3abbb2c557bd)

![IMG_897E6813F79A-3.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/dd0929a8-5726-4117-a035-d56fd9a66757)
