### ISSUE TITLE
Show app version number on the debug screen

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#578]
**Description:**
Display the app version number right away on the debug menu when shaking the device

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.1(137) on an iPhone 7.

![IMG_1AE60190F91D-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/e8a94e11-dc26-412c-8c4e-77929aad3f6b)
