### ISSUE TITLE
Wallet Backups: User has backups enabled but still receives the prompt modal asking them to backup their wallet

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#579]
**Description:**
Modal asked me if I wanted to set up backups for my wallet after my 2nd time sending txtr, but I already have backups enabled...

**What did you expect to happen:**
That modal to not show up bc I already have backups configured

**Reporter:**
Tal

**Device Information:**
Network: rincewind
Phone: iPhone X
iOS: 13.6.1
App version: 0.4.0
App build: 136
App environment: production
Reachability: WiFi ✅
Base node (t-tbn-sydney): Sync failed ❌
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs:**
[2020-08-24_01-42-28-bug-report.zip](https://github.com/tari-project/wallet-ios/files/5116925/2020-08-24_01-42-28-bug-report.zip)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.1 (139) on an iPhone 7.

Video: https://drive.google.com/drive/folders/17PPL0qtm_EBIRbSjHTVgxJHFTQRNfdqD
