### ISSUE TITLE
[Client BE/FE] New user - Authorize local authentication

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#58]
See specs in [#993](https://github.com/tari-project/tari/issues/993)

**Comment by Jasonvdb** [comment]
What I've done for this so long is the first time the user opens the app, they're presented with a "Create Wallet" button. Once they tap the button, the wallet is created and then we request face ID auth with fallback to the password. 

The spec https://github.com/tari-project/tari/issues/993 mentioned a CTA button "Log in with Face ID" but I'm not sure if that's a second button to pop in after the "Create Wallet" button. So for now there's just one "Create Wallet" button that both creates the wallet and requests access. I'm guessing this might change when we get the spec for the onboarding screens so going with this for now. The auth is implemented and changing which button it requests access on would be a small update.

![IMG_2589](https://user-images.githubusercontent.com/5300488/69538191-6a354180-0f8a-11ea-8645-6ef42e506766.PNG)

**Comment by talmahaj** [comment]
@Jasonvdb Thx for explaining. That sounds great, def an easy change if need be
