### ISSUE TITLE
Transaction List screen: Status bar is cut off

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#583]
**Description:**
Status bar on the transaction list screen appears cut off.

**Reporter:**
Tal

**Device Information:**
Network: rincewind
Phone: iPhone X
iOS: 13.6.1
App version: 0.4.0
App build: 136
App environment: production
Reachability: WiFi ✅
Base node (t-tbn-ncal): Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs:**
[2020-08-24_08-03-25-bug-report.zip](https://github.com/tari-project/wallet-ios/files/5119101/2020-08-24_08-03-25-bug-report.zip)

**Screenshot:**
![image0](https://user-images.githubusercontent.com/50987039/91071079-05516980-e638-11ea-8f3a-b0d6a0b7baa1.png)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.1(137) on an iPhone 7.

Video: https://drive.google.com/drive/folders/17PPL0qtm_EBIRbSjHTVgxJHFTQRNfdqD

![IMG_AE7FAF241164-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/1f05f88f-3d0e-476c-abeb-8827ec2e9501)
