### ISSUE TITLE
Idea: Styled QR codes within the mobile wallets

### ISSUE THREAD

**Issue by delta1** [tari-project/wallet-ios#584]
It might look cool to have colourful or styled QR codes in the mobile wallet! 

I saw this site https://www.qrpicture.com/ that uses code in https://github.com/xyzzy/qrpicture to generate QR codes with colors/images 

**Possible issues are**

1. some scanners might not deal well with the fancier graphics 
2. how to integrate the library or redevelop it or find an alternative
3. if using the linked library above, the licence is AGPL and so not compatible with MIT/BSD 

But it does look cool :D 

![example](https://nomatter.tari.com/files/tceqiixr8pf3z8mbtxohmgyfgh/public?h=Uy4OsABxpbEoezC6FJ35oCaqrimvpl6MWKtiGggqWvM)

**Comment by Tas4tari** [comment]
Thank you @delta1
