### ISSUE TITLE
Sending Tari: Blank screen received after user sends Tari and the transaction progress screens are displayed

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#588]
**Description:**
I send 1900 tari to taribot. I got the loading bar but after that was complete the screen went white.

**What did you expect to happen?**
To be returned to the main page.

**Reporter:**
John Georgantas

**Network Information:**
Network: rincewind
Phone: iPhone 11
iOS: 13.5.1
App version: 0.4.0
App build: 136
App environment: production
Reachability: WiFi ✅
Base node (t-tbn-stockholm): Synced ✅
Tor ports: Open ✅
Tor status: Connected ✅
Tor bootstrap progress: 100%

**Logs:**
[2020-08-26_21-35-03-bug-report.zip](https://github.com/tari-project/wallet-ios/files/5134484/2020-08-26_21-35-03-bug-report.zip)

**Comment by Tas4tari** [comment]
@kukabi I see that you have a PR merged for this. can we move this to In Progress or UAT?

**Comment by kukabi** [comment]
yep, UAT 👍🏼

**Comment by Tas4tari** [comment]
@kukabi I've moved it to Merged, Not Yet Released until there is a build out on TestFlight

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS on version 0.4.1 (139) on an iPhone 7.

![IMG_F75A72191435-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/289b4a31-ecae-41fa-b4b0-b16c5e9ce906)

**Comment by Anziskavds** [comment]
This tested unsuccessfully on iOS on an iPhone 7, Testflight version 0.5.0. https://drive.google.com/file/d/1l9Sygm0MUzzYi5h8p42H9Ut0CRD9Kxjg/view?usp=sharing
