### ISSUE TITLE
Users are unable to navigate to Telegram using the links from within the TTL store on the mobile wallet

### ISSUE THREAD

**Issue by Tas4tari** [tari-project/wallet-ios#591]
**Description:**
If the user opens up the TTL store within the wallet app, navigates to "Learn more" > "How to earn" and selects the "Tari Telegram" link, they receive an error message and are not linked to Telegram.

**Additional Notes:**
2 users have submitted bug reports with regards to this and @Tas4tari has confirmed this as itr has occurred on both iOS and Android. 
I have discussed this with Robin and he thinks it could have something to do with regards to the implementation of the web view within the app

**Video:**
https://drive.google.com/file/d/1RuZjdK1PFemrWAxieM7WD7nJ2Mcvn-p-/view?usp=sharing

**Screenshot:**
![photo_2020-08-28 10 35 19](https://user-images.githubusercontent.com/50987039/91583490-96cf1d00-e951-11ea-9d9c-3ce9ed371055.jpeg)
![photo_2020-08-28 10 35 23](https://user-images.githubusercontent.com/50987039/91583504-9afb3a80-e951-11ea-96d2-0e44875e5356.jpeg)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.1 (139) on an iPhone 7.

Video: https://drive.google.com/drive/folders/17PPL0qtm_EBIRbSjHTVgxJHFTQRNfdqD

![IMG_0898.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7a881dc5-2a4e-4e6a-8e55-088a142311d1)

![IMG_0899.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/a15542b8-6d18-46bc-a3f6-354eff50a7d8)
