### ISSUE TITLE
iOS app not opening

### ISSUE THREAD

**Issue by lalanza808** [tari-project/wallet-ios#592]
**Describe the bug**
I click the app and it promptly closes.

**To Reproduce**
1. Click the app
2. See a black screen
3. Watch it close

**Smartphone (please complete the following information):**
 - Device: iPhone6s plus
 - OS: 13.6 (17G68)
 - Version: Tari iOS app version 0.4.0

I've tried killing the background instance of the app and restarting the phone; neither solved the issue.

**Comment by kukabi** [comment]
thanks for the report @lalanza808, will be looked into 👍

**Comment by kukabi** [comment]
Much probably the same as #623.

**Comment by lalanza808** [comment]
This is now resolved with the latest update.

**Comment by kukabi** [comment]
Thanks a lot for the feedback @lalanza808.
