### ISSUE TITLE
Add Amount screen numpad design update.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#601]
**Describe the bug**
Current iOS numpad is based on this design: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5df9171a3e265e1a1d69f626

This is the more recent design that should be implemented: https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/screen/5e69f93345b013115fa03cd7

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.1 (140) on an iPhone 7.

![IMG_76285E48BE20-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d65aea3b-e74d-447f-a7fa-fb87ff9ff893)
