### ISSUE TITLE
Transaction details screen i18n bugs.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#604]
**Describe the bug**
Screenshot below describes.

**To Reproduce**
1. Go to transaction details.

**Screenshots**
![IMG_8638](https://user-images.githubusercontent.com/2969501/91981568-b7242080-ed31-11ea-8106-f91617db2309.PNG)

**Comment by Anziskavds** [comment]
Tested successfully on iOS on version 0.4.1 (140) on an iPhone 7.

![IMG_0916.PNG](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4ba02043-06cf-48fc-90d9-f272e05d89c5)

![IMG_0917.jpg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/4b2fd18e-22ea-4ef6-8c2c-312f0dc6d6b9)
