### ISSUE TITLE
Display better message for too many faucet requests.

### ISSUE THREAD

**Issue by kukabi** [tari-project/wallet-ios#616]
Current message for this case is misleading:
![Screen Shot 2020-10-09 at 16 08 59](https://user-images.githubusercontent.com/2969501/95586747-c93c6180-0a49-11eb-941d-93222c030791.png)

**To Reproduce**
1. Try a clean install on an IP that has already hit the request limit.

**Expected behavior**
The app should display a descriptive message.

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any

**Comment by TruszczynskiA** [comment]
It's no longer an issue.
