### ISSUE TITLE
Transactions failing to send in iOS Aurora Wallet v0.6.0

### ISSUE THREAD

**Issue by karbonbased** [tari-project/wallet-ios#632]
Aurora Wallet is sending an error message when trying to send tXTR on the Stibbons testnet

![IMG_5898](https://user-images.githubusercontent.com/16564599/106948049-dcf28e80-66f0-11eb-9717-5fa0b152f49b.PNG)

iPhone 7 Plus
iOS 14.2

**Comment by kukabi** [comment]
Hi @karbonbased, thanks for the report. What build are you on? It might be related to an issue in `v0.6.0 b160`, which was fixed with a more recent build. Can you please have a clean install of `v0.6.0 b161` from TestFlight and try again?

**Comment by karbonbased** [comment]
Nice, I updated my wallet. I think the person I was trying to send to was on an older wallet too. Closing this issue.
