### ISSUE TITLE
Fee mismatch

### ISSUE THREAD

**Issue by delta1** [tari-project/wallet-ios#634]
Hi @kukabi - regarding the fee estimate mismatch: the FFI function `wallet_send_transaction` should be supplied the *fee per gram* and not the absolute fee for the transaction - [link here](https://github.com/tari-project/wallet-ios/blob/d3334f86ab361d564f8647abad382c1e78e7780f/MobileWallet/TariLib/Wrappers/Wallet.swift#L372) 

This means that for 1 input 1 kernel and 2 outputs (total weight 30 grams) at 100 uT per gram, the fee estimate of 3000 uT is correct. When the transaction is sent, 3000 uT is being given to `wallet_send_transaction` as the fee per gram, which is why the actual fee is then (30 * 3000 uT = 90000 uT) 

I believe the fix would be supplying `Wallet.defaultGramFee` in place of `fee` 

Please let me know if I can help any further! Cheers

**Comment by kukabi** [comment]
It works, will include the solution in the next update.
