### ISSUE TITLE
[Feature] New transaction: Add a note to a transaction

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#76]
See parent ticket [here](https://github.com/tari-project/tari/issues/1059)

**Comment by Tas4tari** [comment]
Closing issue as this has been merged

**Comment by kukabi** [comment]
Reopened: alias not shown in header if the recipient is a contact. Fix in progress. @SerhiiShovkoplias

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS version 0.1.12 (iPhone 7). @kukabi @Tas4tari 

UX/UI

Refer to the following group Zeplin screens -- they're in 1x for iOS so just convert 1:1 from pt to dp for Android.
https://app.zeplin.io/project/5dbdf1a40bdfd3832e35c9c5/dashboard?seid=5df9244ae677e717f5908bd7 - **Test unsuccessfully**

Navigation

Persistent back button should return the user to Recipient screen (which should be reset to default with no recipient selected, a la Paypal) - **Tested unsuccessfully. After the back button was clicked on the transaction note screen I was navigated to add an amount screen.**

Recipient's collapsed Emoji ID or Contact Name should appear at top of nav bar - **Tested unsuccessfully, if the Emoji ID isn't saved as a contact the Emoji ID doesn't show. Only the contact name shows when the Emoji ID is saved as a contact.**

If user taps collapsed Emoji ID, should expand per zpl.io/amwokBD - **Tested unsuccessfully, if the Emoji ID isn't saved as a contact the Emoji ID doesn't show. Only the contact name shows when the Emoji ID is saved as a contact and by clicking on the contact name the Emoji ID doesn't show**

When Emoji ID is expanded, the user can tap anywhere on the screen to collapse it (without triggering any of the actions underneath) -  **Tested unsuccessfully, if the Emoji ID isn't saved as a contact the Emoji ID doesn't show. Only the contact name shows when the Emoji ID is saved as a contact and by clicking on the contact name the Emoji ID doesn't show**


![IMG_91EFB2D4E169-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/13a201ec-95ee-4443-8b68-543c4ce928fa)

![IMG_D8BD40CAA7F9-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ba30f6c4-2703-4d0d-9ea6-bbb5ef421abb)

![IMG_B9D82BC1F704-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/ec1bcc7f-d49a-4caf-9403-70b74ea2f0fe)

**Comment by kukabi** [comment]
@talmahaj The [original ticket](https://github.com/tari-project/tari/issues/1059) mentions that the back button in Add Note screen should take the user back to Add Recipient. Is this really the desired behavior? So far it's been taking the user back to the previous screen, which is Add Amount, and I think it is the expected UX.

**Comment by talmahaj** [comment]
@kukabi oops, that's a mistake on my part, you're right that the user should be sent back to the add amount screen. Sorry for the confusion everyone! @Anziskavds @SerhiiShovkoplias

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.15. Tested on an iPhone 7:

- UX/UI - Tested successfully
- Acceptance Criteria - Navigation - Tested successfully
- Acceptance Criteria - Navigation bar - Tested successfully
- Input and CTA - Tested successfully

Tested according to https://github.com/tari-project/tari/issues/1059 and the above comment of Tal.

![IMG_92BE85990086-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2800db1f-fbe1-4d0b-a523-2069f60d79c0)

![IMG_A32C1867C90F-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/2d8ea295-755e-4236-9ac1-cea7ff0ee445)

![IMG_60797B27DD77-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d53c86ed-f509-48d3-9447-e64bc139bf93)

![IMG_D95287F2BAA5-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7d0784d7-4dd7-4cc0-b1b5-360b333ff777)
