### ISSUE TITLE
[Feature] New transaction: Add an amount

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#77]
See parent ticket [here](https://github.com/tari-project/tari/issues/1058)

**Comment by Jasonvdb** [comment]
Most animations I don't see being too long to implement except for the animating of each digit of the amount. iOS doesn't support out the box animating each char separately while still maintaining a font size the fits the bounds. If I can see it taking too long I might create a separate iOS issue for that and circle back so it doesn't hold up the more critical features.

**Comment by Jasonvdb** [comment]
@semihcihan for this one I'm busy working on the view just before this one (https://github.com/tari-project/wallet-ios/issues/79). So you will have to work on this VC separately and then once my part is done you can slot this in after. Once you see the zeplin designs it'll make more sense.

At the top you'll see an emoji ID, just put a placeholder view there for now, Gabriel is working on a reusable component for that (https://github.com/tari-project/wallet-ios/issues/131). 

For the balance validation check, the available balance you get from the wallet lib like:

```
let (availableBalance, availableBalanceError) = wallet.availableBalance
guard availableBalanceError == nil else {
        throw availableBalanceError!
}
```

**Comment by Tas4tari** [comment]
Closing issue as this has been merged
cc @talmahaj @Jasonvdb

**Comment by kukabi** [comment]
Reopened: alias not shown in header if the recipient is a contact. Fix in progress. @SerhiiShovkoplias

**Comment by Anziskavds** [comment]
Tested successfully on iOS version 0.1.12 on an iPhone 7. I tested according to the parent https://github.com/tari-project/tari/issues/1058 provided.

![IMG_824649D74F0D-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/8771ab93-fb4c-4eb8-8066-ccde0aec6f1c)

![IMG_95193B36D2EB-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/d81e1875-b4e8-4ad6-992d-ffcc55f77291)

![IMG_BAADB2F629EA-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/b8cd9998-d66b-4a07-9305-f8836f2be4d1)

![IMG_726F561EA523-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/887e712e-880b-4bf2-ad3a-db7f832ca73a)

![IMG_4B95DEF0CF2E-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/187a8292-bd5f-4188-ba99-f22ef57bbaea)

![IMG_F3F5A4D3AE38-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/502ed8d5-41c9-4ec7-b69b-70d907cb837a)
