### ISSUE TITLE
[Feature] New transaction: Add recipient by Emoji ID or Contact Name

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#78]
@talmahaj commented on [Mon Nov 25 2019](https://github.com/tari-project/wallet-android/issues/60)

See parent ticket [here](https://github.com/tari-project/tari/issues/1057)

**Comment by kukabi** [comment]
Reopened: recently transacted non-contact recipients not listed. Fix in progress. @SerhiiShovkoplias

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS version 0.1.12 on an iPhone 7. @kukabi 

- Second section of list should be called "Contacts" and display a descending alphabetical list (0-9, A-Z) of all of your Contacts - Tested unsuccessfully 

![IMG_D5C0811319D6-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/520d6382-794a-4d9e-bc37-c4c30a8cd094)

- If a filtered list includes both emoji IDs and Contact Names - e.g. if I type a smiley face emoji, and that emoji is a substring match for 3 recent transactions, only 1 of which has a contact name saved -- then Contact Names should always appear first before emoji-only users - Tested unsuccessfully

![IMG_26E3930376DD-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/aa7a4a78-5fdd-44ec-8c92-3df2a658716b)

Everything else tested successfully :

![IMG_A100F98B77DA-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/9b6fd364-8478-4456-85c9-00a0593f4b1b)

![IMG_511A67B0F271-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/300fbb2d-af88-48db-a71d-25ac117e6b60)

![IMG_D951E521FAE8-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/6f0029f0-ffa7-4817-8848-b62c6c6314cd)

![IMG_B982F6C2BC88-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/95faad11-8cbd-4e93-8dd7-c8f8524f992f)

![IMG_14ADEF3706D5-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/21d7893b-a3a6-43d0-8ef6-e8f84692c2f7)

![IMG_7FE7EF997134-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/0a86ab0c-de24-466c-9a08-d7a0fbe0ac8c)

![IMG_7FE7EF997134-1 2.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/7a2ccda3-729a-4d7b-b41f-d0b0097f6a5a)

![IMG_6DDDBE4EF698-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/f2fbb380-0740-4cdd-9e12-ffd9de95ee76)

![IMG_81F195A17B7C-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/27113a85-5451-4989-a596-38c32773dd21)

**Comment by Anziskavds** [comment]
Tested unsuccessfully. Taribot shows as the first contact on the list and according to the requirements the contacts should show alphabetically. @kukabi 

![IMG_7892CFEA675A-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/01128d05-60dc-4f9c-8eef-3bb22b62bdc2)

**Comment by Anziskavds** [comment]
Tested unsuccessfully on iOS version 0.2.0 on an iPhone 7. @kukabi @SerhiiShovkoplias @Jasonvdb 

- Second section of the list should be called "Contacts" and display a descending alphabetical list (0-9, A-Z) of all of your Contacts.
- Taribot shows as the first contact on the list and according to the requirements the contacts should show alphabetically.
- If a filtered list includes both emoji IDs and Contact Names - e.g. if I type a smiley face emoji, and that emoji is a substring match for 3 recent transactions, only 1 of which has a contact name saved -- then Contact Names should always appear first before emoji-only users.

![IMG_0F2F0B21635D-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/391f2816-3340-4326-9fea-8ad23addb5c7)

![IMG_510838E8819F-1.jpeg](https://images.zenhubusercontent.com/5cdd14f21f980125322a448a/795e9e23-222e-4f80-bf38-e777e36b8d41)

**Comment by Anziskavds** [comment]
As discussed in stand up 2020/06/23 I'm closing off this card because Tal mentioned that this is a minor issue and don't need to worry about it that much.

cc @Tas4tari @talmahaj @SerhiiShovkoplias
