### ISSUE TITLE
[Feature] Sending Tari: Adding a recipient by QR Code

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#88]
See [parent](https://github.com/tari-project/tari/issues/1174)

**Comment by lupugabriel** [comment]
@talmahaj @Jasonvdb @CjS77
For the presentation style i used the new iOS 13 presentation style. You can see a little bit on top the previous page and it's very easy to swipe down and return to the previous page. Do you want to use this or to do like in design? @Jasonvdb asked me to put this question on github.

[https://www.dropbox.com/s/5qvl1os8zzl52qn/IMG_4698.PNG?dl=0](url)

**Comment by Jasonvdb** [comment]
@Karim-tari ☝️

**Comment by Jasonvdb** [comment]
@talmahaj what copy do you want to use for when requesting permission to use the camera?

**Comment by talmahaj** [comment]
@Jasonvdb @lupugabriel I'm so sorry for the delays on all these answers; these accidentally all got filed into the wrong email folder with my personal github stuff, and I'm just seeing them all now.

- I'm guessing "[Appname] would like to access the camera" is the part of the permissions alert we can't change given I see it everywhere, so maybe underneath just something simple like "The camera is only used when scanning QR codes" -- though I'm open to other ideas, I don't feel strongly.

- @lupugabriel that dropbox link doesn't work anymore, can you reupload? Thanks!
