### ISSUE TITLE
[Feature] Wallet Info/Profile

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#94]
See [parent](https://github.com/tari-project/tari/issues/1179)

**Comment by CjS77** [comment]
Parent is closed.

What info should we indicate i the QR code?

At the bare minimum, we must display a pubkey (aka emoji ID) - 64 characters = 32 byte hex-encoded pubkry.
For MVP, do we want to include an alias as well (up to 32 chars, say?)

The QR code should resolve to JSON, as follows

```
{ "pubkey":"0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
  "alias":"12345678901234567890123456789012"
}
```
With an alias, we still have a manageable QR code:

![frame](https://user-images.githubusercontent.com/7573551/72257884-62eaf580-3615-11ea-9d5a-52dc9b245fde.png)
