### ISSUE TITLE
Transaction Send Screen - Improvements

### ISSUE THREAD

**Issue by TruszczynskiA** [tari-project/wallet-ios#953]
We are in the process of updating the UI/UX of the most commonly used screens in the app. The transaction send screen is one of the screens that need to be updated.

**Definition of done:**

- The transaction send screen was updated to the designs.

**Comment by Simeon221** [comment]
cc37a933433d4e9de88351f674090a7aa950762e

**Comment by Simeon221** [comment]
fa2a8ffd28fa07fed93f2b79892bad94f4a8b886c0f777fe15a04f78365bcd9b
