### ISSUE TITLE
[Feature] New user - splash screen and loading sequence

### ISSUE THREAD

**Issue by talmahaj** [tari-project/wallet-ios#97]
[See parent](https://github.com/tari-project/tari/issues/991)

**Comment by lupugabriel** [comment]
@CjS77 @Jasonvdb we need to come back to this task once Karim saves the latest version of the videos. I sent him a picture with some changes i requested ( Should not be black distance on top and bottom of the animations). Can you please tag karim. I dont know why but he does not appear here when i try to tag him. thanks.

**Comment by talmahaj** [comment]
@lupugabriel I forwarded this to him, thanks!
